"""Calculus catalog: limits through related rates."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "calculus"

TOPICS = (
    TopicSpec("calc-limits", SUBJECT_ID, "Limits", "What a function approaches.", ("calc_limits",), "CALC-LIM-001"),
    TopicSpec("calc-derivatives", SUBJECT_ID, "Derivatives", "Instantaneous rate of change.", ("calc_derivatives",), "CALC-DER-001"),
    TopicSpec("calc-integrals", SUBJECT_ID, "Integrals", "Accumulation and area.", ("calc_integrals",), "CALC-INT-001"),
    TopicSpec("calc-optimization", SUBJECT_ID, "Optimization", "Maxima and minima from derivatives.", ("calc_opt",), "CALC-OPT-001"),
    TopicSpec("calc-related-rates", SUBJECT_ID, "Related Rates", "How linked quantities change together.", ("calc_rates",), "CALC-RR-001"),
    TopicSpec("calc-sequences", SUBJECT_ID, "Sequences", "Lists of numbers following a rule.", ("calc_seq",), "CALC-SEQ-001"),
    TopicSpec("calc-series", SUBJECT_ID, "Series", "Sums of sequence terms.", ("calc_series",), "CALC-SER-001"),
    TopicSpec("calc-chain", SUBJECT_ID, "Chain Rule", "Differentiate compositions.", ("calc_chain",), "CALC-CH-001"),
    TopicSpec("calc-ftc", SUBJECT_ID, "Fundamental Theorem", "Derivatives and integrals as inverses.", ("calc_ftc",), "CALC-FTC-001"),
    TopicSpec("calc-implicit", SUBJECT_ID, "Implicit Differentiation", "Differentiate relations that are not y = f(x).", ("calc_implicit",), "CALC-IMP-001"),
)

CONCEPTS = (
    ConceptSpec("calc_limits", "calc-limits", SUBJECT_ID, "Limits", "The value a function approaches."),
    ConceptSpec("calc_derivatives", "calc-derivatives", SUBJECT_ID, "Derivatives", "Slope of the tangent; instantaneous rate."),
    ConceptSpec("calc_integrals", "calc-integrals", SUBJECT_ID, "Integrals", "Net accumulation of a rate."),
    ConceptSpec("calc_opt", "calc-optimization", SUBJECT_ID, "Optimization", "Critical points and extrema."),
    ConceptSpec("calc_rates", "calc-related-rates", SUBJECT_ID, "Related rates", "Differentiate both sides with respect to time."),
    ConceptSpec("calc_seq", "calc-sequences", SUBJECT_ID, "Sequences", "A function from counting numbers to values."),
    ConceptSpec("calc_series", "calc-series", SUBJECT_ID, "Series", "Adding the terms of a sequence."),
    ConceptSpec("calc_chain", "calc-chain", SUBJECT_ID, "Chain rule", "Derivative of a composition."),
    ConceptSpec("calc_ftc", "calc-ftc", SUBJECT_ID, "Fundamental Theorem of Calculus", "Accumulation and rates are inverses."),
    ConceptSpec("calc_implicit", "calc-implicit", SUBJECT_ID, "Implicit differentiation", "Differentiate both sides of an equation."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("CALC-LIM-001", SUBJECT_ID, "calc-limits", "calc_limits", 2, "CONCEPT_CHECK",
       "lim x→2 of (x + 1) equals:",
       "3",
       "The function is continuous, so the limit is the value 2 + 1 = 3.",
       cues=("continuous", "substitute", "approach")),
    ch("CALC-LIM-002", SUBJECT_ID, "calc-limits", "calc_limits", 3, "DIRECT",
       "What is lim x→0 of (sin x) / x ?",
       "1",
       "This is a standard trigonometric limit: sin x over x approaches 1.",
       cues=("sin x", "standard", "1")),
    ch("CALC-LIM-003", SUBJECT_ID, "calc-limits", "calc_limits", 3, "ERROR_ANALYSIS",
       "A student says lim x→0 of 1/x is 0 because x is tiny. Where did they go wrong?",
       "1/x grows without bound; the two-sided limit does not exist",
       "As x approaches 0 from the right, 1/x → +∞; from the left it → −∞. That is not 0.",
       cues=("infinity", "two-sided", "does not exist")),
    ch("CALC-LIM-004", SUBJECT_ID, "calc-limits", "calc_limits", 2, "TRUE_FALSE",
       "True or false: a limit can exist even if the function is not defined at that point.",
       "True",
       "Limits care about nearby values. A hole at the point does not by itself prevent a limit.",
       choices=("True", "False"),
       cues=("nearby", "hole", "defined")),
    ch("CALC-DER-001", SUBJECT_ID, "calc-derivatives", "calc_derivatives", 2, "CONCEPT_CHECK",
       "The derivative of a function at a point is best described as:",
       "The instantaneous rate of change / slope of the tangent",
       "f'(a) is the slope of the tangent line at x = a, the instantaneous rate of change.",
       choices=(
           "The instantaneous rate of change / slope of the tangent",
           "The area under the curve",
           "The average of all y-values",
           "A random slope",
       ),
       cues=("tangent", "instantaneous", "slope")),
    ch("CALC-DER-002", SUBJECT_ID, "calc-derivatives", "calc_derivatives", 3, "DIRECT",
       "If f(x) = x², what is f'(x)?",
       "2x",
       "Power rule: d/dx x^n = n x^{n-1}, so d/dx x² = 2x.",
       cues=("power rule", "2x", "n-1")),
    ch("CALC-DER-003", SUBJECT_ID, "calc-derivatives", "calc_derivatives", 3, "PREDICTION",
       "f(x) = 3x + 5. What is f'(x)?",
       "3",
       "The derivative of a linear function is its slope, here 3.",
       cues=("slope", "linear", "constant")),
    ch("CALC-DER-004", SUBJECT_ID, "calc-derivatives", "calc_derivatives", 4, "TRANSFER",
       "Position is s(t) = t² meters. What is the velocity at t = 3 s?",
       "6 m/s",
       "Velocity is s'(t) = 2t. At t = 3, velocity is 6 m/s.",
       cues=("velocity", "derivative", "2t"), strategies=("INCREASE", "MAINTAIN")),
    ch("CALC-INT-001", SUBJECT_ID, "calc-integrals", "calc_integrals", 2, "CONCEPT_CHECK",
       "A definite integral of a rate over an interval measures:",
       "Net accumulation (signed area)",
       "∫_a^b f represents net signed area, the accumulation of f from a to b.",
       choices=("Net accumulation (signed area)", "The slope at a point", "A random sample", "The maximum value only"),
       cues=("area", "accumulation", "net")),
    ch("CALC-INT-002", SUBJECT_ID, "calc-integrals", "calc_integrals", 3, "DIRECT",
       "What is ∫ 2x dx ?",
       "x² + C",
       "The antiderivative of 2x is x² plus a constant.",
       cues=("antiderivative", "power", "constant")),
    ch("CALC-INT-003", SUBJECT_ID, "calc-integrals", "calc_integrals", 3, "APPLICATION",
       "Speed is constantly 4 m/s for 5 s. How far do you travel?",
       "20 m",
       "Distance is the integral of speed: 4 × 5 = 20 m.",
       cues=("distance", "rate", "time")),
    ch("CALC-INT-004", SUBJECT_ID, "calc-integrals", "calc_integrals", 4, "COMPARE",
       "How are derivatives and definite integrals related by the Fundamental Theorem?",
       "Differentiating an accumulation function recovers the original rate",
       "FTC says the derivative of ∫_a^x f is f(x) (under stated conditions).",
       cues=("fundamental theorem", "accumulation", "recover")),
    ch("CALC-OPT-001", SUBJECT_ID, "calc-optimization", "calc_opt", 3, "CONCEPT_CHECK",
       "To find interior maxima of a smooth f, you should first look at points where:",
       "f'(x) = 0 or f' is undefined",
       "Critical points are where the derivative is zero or does not exist.",
       choices=("f'(x) = 0 or f' is undefined", "f(x) = 0 only", "x = 0 only", "The function is odd"),
       cues=("critical", "derivative zero", "undefined")),
    ch("CALC-OPT-002", SUBJECT_ID, "calc-optimization", "calc_opt", 3, "DIRECT",
       "f(x) = x² on [−1, 2]. Where is the minimum?",
       "x = 0",
       "f' = 2x = 0 at x = 0, and f(0) = 0 is smaller than the endpoint values 1 and 4.",
       cues=("critical", "endpoints", "minimum")),
    ch("CALC-OPT-003", SUBJECT_ID, "calc-optimization", "calc_opt", 4, "SCENARIO",
       "You want a rectangle of perimeter 20 with maximum area. What is the side length of the maximizing shape?",
       "5",
       "P = 2(l+w)=20 so l+w=10. Area lw = l(10−l). Maximum at l = 5, a square.",
       cues=("perimeter", "square", "max area"), strategies=("INCREASE", "MAINTAIN")),
    ch("CALC-RR-001", SUBJECT_ID, "calc-related-rates", "calc_rates", 3, "CONCEPT_CHECK",
       "Related rates problems typically start by:",
       "Writing an equation linking the quantities, then differentiating with respect to time",
       "Relate the variables geometrically or physically, then d/dt both sides.",
       cues=("relate", "differentiate", "time")),
    ch("CALC-RR-002", SUBJECT_ID, "calc-related-rates", "calc_rates", 4, "APPLICATION",
       "A circle's radius grows at 2 cm/s. How fast is area growing when r = 5? (Use A = πr².)",
       "20π cm²/s",
       "dA/dt = 2πr dr/dt = 2π·5·2 = 20π cm²/s.",
       cues=("2πr", "chain rule", "dr/dt"), strategies=("INCREASE", "MAINTAIN")),
    ch("CALC-RR-003", SUBJECT_ID, "calc-related-rates", "calc_rates", 3, "ERROR_ANALYSIS",
       "A student differentiates A = πr² to get dA/dt = πr². What did they forget?",
       "The chain rule: r depends on t, so a factor 2r dr/dt is needed",
       "r is a function of time. Differentiating r² with respect to t requires 2r dr/dt.",
       cues=("chain rule", "dr/dt", "2r")),
    ch("CALC-SEQ-001", SUBJECT_ID, "calc-sequences", "calc_seq", 2, "NUMERIC",
       "The sequence a_n = 2n. What is a_5?", "10",
       "Plug in n = 5: 2×5 = 10.",
       cues=("term", "plug in", "10"), family="CALC-SEQ", representation="numeric"),
    ch("CALC-SEQ-002", SUBJECT_ID, "calc-sequences", "calc_seq", 3, "CONCEPT_CHECK",
       "A sequence is best described as:",
       "An ordered list of numbers generated by a rule",
       "Each position n has a term a_n.",
       choices=("An ordered list of numbers generated by a rule", "A random cloud of numbers", "Only a graph", "A derivative"),
       cues=("ordered", "term", "n"), family="CALC-SEQ"),
    ch("CALC-SER-001", SUBJECT_ID, "calc-series", "calc_series", 2, "NUMERIC",
       "1 + 2 + 3 + 4 equals:", "10",
       "This finite series adds the first four positive integers.",
       cues=("sum", "series", "10"), family="CALC-SER", representation="numeric"),
    ch("CALC-SER-002", SUBJECT_ID, "calc-series", "calc_series", 3, "TRUE_FALSE",
       "True or false: a series is a sum of sequence terms.",
       "True",
       "A series adds a_1 + a_2 + … (finite or infinite).",
       choices=("True", "False"),
       cues=("sum", "terms"), family="CALC-SER"),
    ch("CALC-CH-001", SUBJECT_ID, "calc-chain", "calc_chain", 3, "DIRECT",
       "If y = (3x + 1)², dy/dx equals:",
       "2(3x+1)·3",
       "Outer 2u, inner 3: 2(3x+1)·3.",
       cues=("chain", "outer", "inner"), family="CALC-CH", representation="symbolic"),
    ch("CALC-CH-002", SUBJECT_ID, "calc-chain", "calc_chain", 3, "EXPLAIN_CHOICE",
       "Why is the chain rule needed for sin(2x)?",
       "2x is a composition: sine of an inner function",
       "You differentiate sine and multiply by the derivative of 2x.",
       choices=(
           "2x is a composition: sine of an inner function",
           "Sine cannot be differentiated",
           "Because 2x is a constant",
           "The chain rule is only for integrals",
       ),
       cues=("composition", "inner", "cosine"), family="CALC-CH"),
    ch("CALC-FTC-001", SUBJECT_ID, "calc-ftc", "calc_ftc", 3, "CONCEPT_CHECK",
       "The Fundamental Theorem of Calculus connects:",
       "Differentiation and integration as inverse processes",
       "The derivative of an accumulation function recovers the integrand.",
       choices=(
           "Differentiation and integration as inverse processes",
           "Limits and logarithms only",
           "Sequences and matrices",
           "Only algebra and geometry",
       ),
       cues=("inverse", "accumulation", "derivative"), family="CALC-FTC"),
    ch("CALC-FTC-002", SUBJECT_ID, "calc-ftc", "calc_ftc", 3, "TRUE_FALSE",
       "True or false: d/dx ∫_0^x t² dt = x² (for x in the interval of continuity).",
       "True",
       "FTC part 1: differentiating the integral from a constant to x returns the integrand at x.",
       choices=("True", "False"),
       cues=("FTC", "upper limit x", "integrand"), family="CALC-FTC"),
    ch("CALC-IMP-001", SUBJECT_ID, "calc-implicit", "calc_implicit", 3, "DIRECT",
       "Differentiate x² + y² = 25 implicitly. What is 2x + 2y y' equal to?",
       "0",
       "Both sides: 2x + 2y y' = 0.",
       cues=("implicit", "both sides", "y'"), family="CALC-IMP", representation="symbolic"),
    ch("CALC-IMP-002", SUBJECT_ID, "calc-implicit", "calc_implicit", 4, "ERROR_ANALYSIS",
       "A student treats y as a constant when differentiating x² + y² = 1 and writes 2x = 0. What is wrong?",
       "y depends on x, so y² needs the chain rule (2y y')",
       "Implicit differentiation treats y as a function of x.",
       cues=("y depends on x", "chain", "2y y'"), family="CALC-IMP"),
)
