"""Chemistry catalog."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "chemistry"

TOPICS = (
    TopicSpec("chem-atomic", SUBJECT_ID, "Atomic Structure", "Protons, neutrons, and electrons.", ("chem_atom",), "CHEM-AT-001"),
    TopicSpec("chem-bonding", SUBJECT_ID, "Chemical Bonding", "Ionic vs covalent bonding.", ("chem_bond",), "CHEM-BO-001"),
    TopicSpec("chem-stoich", SUBJECT_ID, "Stoichiometry", "Moles and balanced equations.", ("chem_stoich",), "CHEM-ST-001"),
    TopicSpec("chem-acids", SUBJECT_ID, "Acids and Bases", "pH and proton transfer.", ("chem_acid",), "CHEM-AB-001"),
    TopicSpec("chem-reactions", SUBJECT_ID, "Chemical Reactions", "Types of reactions and conservation.", ("chem_rxn",), "CHEM-RX-001"),
)

CONCEPTS = (
    ConceptSpec("chem_atom", "chem-atomic", SUBJECT_ID, "Atomic structure", "Nucleus and electron cloud."),
    ConceptSpec("chem_bond", "chem-bonding", SUBJECT_ID, "Chemical bonds", "How atoms stick together."),
    ConceptSpec("chem_stoich", "chem-stoich", SUBJECT_ID, "Stoichiometry", "Quantitative relations in reactions."),
    ConceptSpec("chem_acid", "chem-acids", SUBJECT_ID, "Acids and bases", "pH and neutralization."),
    ConceptSpec("chem_rxn", "chem-reactions", SUBJECT_ID, "Reaction types", "What changes in a chemical reaction."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("CHEM-AT-001", SUBJECT_ID, "chem-atomic", "chem_atom", 1, "CONCEPT_CHECK",
       "The atomic number of an element is the number of:",
       "Protons",
       "Atomic number counts protons in the nucleus and identifies the element.",
       choices=("Protons", "Neutrons only", "Molecules", "Bonds"),
       cues=("protons", "atomic number", "identity")),
    ch("CHEM-AT-002", SUBJECT_ID, "chem-atomic", "chem_atom", 2, "DIRECT",
       "Carbon-12 has 6 protons. How many electrons does a neutral carbon atom have?",
       "6",
       "A neutral atom has equal protons and electrons.",
       cues=("neutral", "equal", "electrons")),
    ch("CHEM-AT-003", SUBJECT_ID, "chem-atomic", "chem_atom", 3, "COMPARE",
       "What differs between isotopes of the same element?",
       "Number of neutrons",
       "Isotopes share proton number (element) but differ in neutrons, so mass number changes.",
       cues=("neutrons", "same protons", "mass")),
    ch("CHEM-BO-001", SUBJECT_ID, "chem-bonding", "chem_bond", 2, "COMPARE",
       "What is a key difference between ionic and covalent bonds?",
       "Ionic bonds transfer electrons; covalent bonds share electrons",
       "Ionic bonding is electron transfer between ions. Covalent bonding is sharing pairs.",
       choices=(
           "Ionic bonds transfer electrons; covalent bonds share electrons",
           "They are identical",
           "Covalent bonds only happen in metals",
           "Ionic bonds are between two nonmetals only",
       ),
       cues=("transfer", "share", "electrons")),
    ch("CHEM-BO-002", SUBJECT_ID, "chem-bonding", "chem_bond", 3, "TRUE_FALSE",
       "True or false: NaCl is held together mainly by covalent sharing of a pair of electrons between Na and Cl.",
       "False",
       "Sodium chloride is ionic: Na⁺ and Cl⁻ attract electrostatically after electron transfer.",
       choices=("True", "False"),
       cues=("ionic", "transfer", "ions")),
    ch("CHEM-BO-003", SUBJECT_ID, "chem-bonding", "chem_bond", 3, "CONCEPT_CHECK",
       "A molecule of O₂ is held by:",
       "A covalent bond",
       "Two nonmetals share electrons in O₂.",
       choices=("A covalent bond", "An ionic bond between metals", "Gravity", "A nuclear force only"),
       cues=("nonmetals", "share", "covalent")),
    ch("CHEM-ST-001", SUBJECT_ID, "chem-stoich", "chem_stoich", 2, "CONCEPT_CHECK",
       "One mole of particles contains how many entities (Avogadro's number, approx.)?",
       "6.02 × 10²³",
       "A mole is 6.02×10²³ specified particles.",
       choices=("6.02 × 10²³", "12", "1000", "6.02"),
       cues=("mole", "Avogadro", "particles")),
    ch("CHEM-ST-002", SUBJECT_ID, "chem-stoich", "chem_stoich", 3, "DIRECT",
       "In 2 H₂ + O₂ → 2 H₂O, how many moles of water form from 1 mole of O₂ (complete reaction)?",
       "2",
       "The ratio O₂ : H₂O is 1 : 2.",
       cues=("ratio", "coefficients", "2")),
    ch("CHEM-ST-003", SUBJECT_ID, "chem-stoich", "chem_stoich", 4, "APPLICATION",
       "You have 4 moles H₂ and 1 mole O₂ for 2 H₂ + O₂ → 2 H₂O. What limits the product?",
       "O₂ is limiting; 2 moles of water form",
       "1 mol O₂ needs 2 mol H₂ and makes 2 mol water. Extra H₂ remains.",
       cues=("limiting", "oxygen", "stoichiometry"), strategies=("INCREASE", "MAINTAIN")),
    ch("CHEM-AB-001", SUBJECT_ID, "chem-acids", "chem_acid", 2, "CONCEPT_CHECK",
       "A pH of 3 compared with pH 5 is:",
       "More acidic (higher [H⁺])",
       "Lower pH means higher hydrogen-ion concentration. pH 3 is more acidic than pH 5.",
       choices=("More acidic (higher [H⁺])", "More basic", "Exactly the same", "Not a number line"),
       cues=("lower pH", "acidic", "hydrogen")),
    ch("CHEM-AB-002", SUBJECT_ID, "chem-acids", "chem_acid", 3, "TRUE_FALSE",
       "True or false: a strong acid completely ionizes in water.",
       "True",
       "Strong acids dissociate essentially fully in aqueous solution.",
       choices=("True", "False"),
       cues=("completely", "ionizes", "strong")),
    ch("CHEM-AB-003", SUBJECT_ID, "chem-acids", "chem_acid", 3, "APPLICATION",
       "HCl + NaOH → NaCl + H₂O is an example of:",
       "Neutralization",
       "An acid and a base form a salt and water.",
       cues=("acid", "base", "salt", "water")),
    ch("CHEM-RX-001", SUBJECT_ID, "chem-reactions", "chem_rxn", 2, "CONCEPT_CHECK",
       "In a chemical reaction, atoms are:",
       "Rearranged but not created or destroyed",
       "Mass and atoms are conserved; bonds break and form.",
       choices=("Rearranged but not created or destroyed", "Deleted", "Converted into new elements routinely", "Ignored"),
       cues=("conserved", "rearranged", "atoms")),
    ch("CHEM-RX-002", SUBJECT_ID, "chem-reactions", "chem_rxn", 3, "SEQUENCE",
       "Balance: H₂ + O₂ → H₂O. The smallest whole-number coefficients are:",
       "2, 1, 2",
       "2 H₂ + O₂ → 2 H₂O balances hydrogen and oxygen.",
       cues=("balance", "coefficients", "2 1 2")),
    ch("CHEM-RX-003", SUBJECT_ID, "chem-reactions", "chem_rxn", 3, "ERROR_ANALYSIS",
       "A student writes 2 H₂ + O₂ → H₂O and says it is balanced because oxygen appears on both sides. What's wrong?",
       "Hydrogen and oxygen atom counts do not match",
       "Left: 4 H and 2 O. Right: 2 H and 1 O. The product coefficient must be 2.",
       cues=("atom count", "not balanced", "coefficients")),
)
