"""Chemistry catalog."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "chemistry"

TOPICS = (
    TopicSpec("chem-atomic", SUBJECT_ID, "Atomic Structure", "Protons, neutrons, and electrons.", ("chem_atom",), "CHEM-AT-001"),
    TopicSpec("chem-bonding", SUBJECT_ID, "Chemical Bonding", "Ionic vs covalent bonding.", ("chem_bond",), "CHEM-BO-001"),
    TopicSpec("chem-stoich", SUBJECT_ID, "Stoichiometry", "Moles and balanced equations.", ("chem_stoich",), "CHEM-ST-001"),
    TopicSpec("chem-acids", SUBJECT_ID, "Acids and Bases", "pH and proton transfer.", ("chem_acid",), "CHEM-AB-001"),
    TopicSpec("chem-reactions", SUBJECT_ID, "Chemical Reactions", "Types of reactions and conservation.", ("chem_rxn",), "CHEM-RX-001"),
    TopicSpec("chem-thermo", SUBJECT_ID, "Thermochemistry", "Heat in chemical change.", ("chem_thermo",), "CHEM-TH-001"),
    TopicSpec("chem-organic", SUBJECT_ID, "Organic Chemistry", "Carbon frameworks and functional groups.", ("chem_organic",), "CHEM-OR-001"),
    TopicSpec("chem-eq", SUBJECT_ID, "Equilibrium", "Forward and reverse rates can match.", ("chem_eq",), "CHEM-EQ-001"),
    TopicSpec("chem-gases", SUBJECT_ID, "Gases", "Pressure, volume, and temperature.", ("chem_gases",), "CHEM-GAS-001"),
    TopicSpec("chem-periodic", SUBJECT_ID, "Periodic Table", "Trends across groups and periods.", ("chem_periodic",), "CHEM-PE-001"),
)

CONCEPTS = (
    ConceptSpec("chem_atom", "chem-atomic", SUBJECT_ID, "Atomic structure", "Nucleus and electron cloud."),
    ConceptSpec("chem_bond", "chem-bonding", SUBJECT_ID, "Chemical bonds", "How atoms stick together."),
    ConceptSpec("chem_stoich", "chem-stoich", SUBJECT_ID, "Stoichiometry", "Quantitative relations in reactions."),
    ConceptSpec("chem_acid", "chem-acids", SUBJECT_ID, "Acids and bases", "pH and neutralization."),
    ConceptSpec("chem_rxn", "chem-reactions", SUBJECT_ID, "Reaction types", "What changes in a chemical reaction."),
    ConceptSpec("chem_thermo", "chem-thermo", SUBJECT_ID, "Thermochemistry", "Exothermic and endothermic change."),
    ConceptSpec("chem_organic", "chem-organic", SUBJECT_ID, "Organic chemistry", "Carbon compounds and functional groups."),
    ConceptSpec("chem_eq", "chem-eq", SUBJECT_ID, "Chemical equilibrium", "Dynamic balance of forward and reverse rates."),
    ConceptSpec("chem_gases", "chem-gases", SUBJECT_ID, "Gas laws", "How P, V, and T relate for a gas."),
    ConceptSpec("chem_periodic", "chem-periodic", SUBJECT_ID, "Periodic trends", "Atomic size and reactivity patterns."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("CHEM-AT-001", SUBJECT_ID, "chem-atomic", "chem_atom", 1, "CONCEPT_CHECK",
       "The atomic number of an element is the number of:",
       "Protons",
       "Atomic number counts protons in the nucleus and identifies the element.",
       choices=("Protons", "Neutrons only", "Molecules", "Bonds"),
       cues=("protons", "atomic number", "identity")),
    ch("CHEM-AT-002", SUBJECT_ID, "chem-atomic", "chem_atom", 2, "DIRECT",
       "Carbon-12 has 6 protons. How many electrons does a neutral carbon atom have?",
       "6",
       "A neutral atom has equal protons and electrons.",
       cues=("neutral", "equal", "electrons")),
    ch("CHEM-AT-003", SUBJECT_ID, "chem-atomic", "chem_atom", 3, "COMPARE",
       "What differs between isotopes of the same element?",
       "Number of neutrons",
       "Isotopes share proton number (element) but differ in neutrons, so mass number changes.",
       cues=("neutrons", "same protons", "mass")),
    ch("CHEM-BO-001", SUBJECT_ID, "chem-bonding", "chem_bond", 2, "COMPARE",
       "What is a key difference between ionic and covalent bonds?",
       "Ionic bonds transfer electrons; covalent bonds share electrons",
       "Ionic bonding is electron transfer between ions. Covalent bonding is sharing pairs.",
       choices=(
           "Ionic bonds transfer electrons; covalent bonds share electrons",
           "They are identical",
           "Covalent bonds only happen in metals",
           "Ionic bonds are between two nonmetals only",
       ),
       cues=("transfer", "share", "electrons")),
    ch("CHEM-BO-002", SUBJECT_ID, "chem-bonding", "chem_bond", 3, "TRUE_FALSE",
       "True or false: NaCl is held together mainly by covalent sharing of a pair of electrons between Na and Cl.",
       "False",
       "Sodium chloride is ionic: Na⁺ and Cl⁻ attract electrostatically after electron transfer.",
       choices=("True", "False"),
       cues=("ionic", "transfer", "ions")),
    ch("CHEM-BO-003", SUBJECT_ID, "chem-bonding", "chem_bond", 3, "CONCEPT_CHECK",
       "A molecule of O₂ is held by:",
       "A covalent bond",
       "Two nonmetals share electrons in O₂.",
       choices=("A covalent bond", "An ionic bond between metals", "Gravity", "A nuclear force only"),
       cues=("nonmetals", "share", "covalent")),
    ch("CHEM-ST-001", SUBJECT_ID, "chem-stoich", "chem_stoich", 2, "CONCEPT_CHECK",
       "One mole of particles contains how many entities (Avogadro's number, approx.)?",
       "6.02 × 10²³",
       "A mole is 6.02×10²³ specified particles.",
       choices=("6.02 × 10²³", "12", "1000", "6.02"),
       cues=("mole", "Avogadro", "particles")),
    ch("CHEM-ST-002", SUBJECT_ID, "chem-stoich", "chem_stoich", 3, "DIRECT",
       "In 2 H₂ + O₂ → 2 H₂O, how many moles of water form from 1 mole of O₂ (complete reaction)?",
       "2",
       "The ratio O₂ : H₂O is 1 : 2.",
       cues=("ratio", "coefficients", "2")),
    ch("CHEM-ST-003", SUBJECT_ID, "chem-stoich", "chem_stoich", 4, "APPLICATION",
       "You have 4 moles H₂ and 1 mole O₂ for 2 H₂ + O₂ → 2 H₂O. What limits the product?",
       "O₂ is limiting; 2 moles of water form",
       "1 mol O₂ needs 2 mol H₂ and makes 2 mol water. Extra H₂ remains.",
       cues=("limiting", "oxygen", "stoichiometry"), strategies=("INCREASE", "MAINTAIN")),
    ch("CHEM-AB-001", SUBJECT_ID, "chem-acids", "chem_acid", 2, "CONCEPT_CHECK",
       "A pH of 3 compared with pH 5 is:",
       "More acidic (higher [H⁺])",
       "Lower pH means higher hydrogen-ion concentration. pH 3 is more acidic than pH 5.",
       choices=("More acidic (higher [H⁺])", "More basic", "Exactly the same", "Not a number line"),
       cues=("lower pH", "acidic", "hydrogen")),
    ch("CHEM-AB-002", SUBJECT_ID, "chem-acids", "chem_acid", 3, "TRUE_FALSE",
       "True or false: a strong acid completely ionizes in water.",
       "True",
       "Strong acids dissociate essentially fully in aqueous solution.",
       choices=("True", "False"),
       cues=("completely", "ionizes", "strong")),
    ch("CHEM-AB-003", SUBJECT_ID, "chem-acids", "chem_acid", 3, "APPLICATION",
       "HCl + NaOH → NaCl + H₂O is an example of:",
       "Neutralization",
       "An acid and a base form a salt and water.",
       cues=("acid", "base", "salt", "water")),
    ch("CHEM-RX-001", SUBJECT_ID, "chem-reactions", "chem_rxn", 2, "CONCEPT_CHECK",
       "In a chemical reaction, atoms are:",
       "Rearranged but not created or destroyed",
       "Mass and atoms are conserved; bonds break and form.",
       choices=("Rearranged but not created or destroyed", "Deleted", "Converted into new elements routinely", "Ignored"),
       cues=("conserved", "rearranged", "atoms")),
    ch("CHEM-RX-002", SUBJECT_ID, "chem-reactions", "chem_rxn", 3, "SEQUENCE",
       "Balance: H₂ + O₂ → H₂O. The smallest whole-number coefficients are:",
       "2, 1, 2",
       "2 H₂ + O₂ → 2 H₂O balances hydrogen and oxygen.",
       cues=("balance", "coefficients", "2 1 2")),
    ch("CHEM-RX-003", SUBJECT_ID, "chem-reactions", "chem_rxn", 3, "ERROR_ANALYSIS",
       "A student writes 2 H₂ + O₂ → H₂O and says it is balanced because oxygen appears on both sides. What's wrong?",
       "Hydrogen and oxygen atom counts do not match",
       "Left: 4 H and 2 O. Right: 2 H and 1 O. The product coefficient must be 2.",
       cues=("atom count", "not balanced", "coefficients")),
    ch("CHEM-TH-001", SUBJECT_ID, "chem-thermo", "chem_thermo", 2, "CONCEPT_CHECK",
       "An exothermic reaction:",
       "Releases heat to the surroundings",
       "The system loses enthalpy as heat; surroundings warm.",
       choices=("Releases heat to the surroundings", "Always absorbs heat", "Creates energy from nothing", "Has no energy change"),
       cues=("releases", "heat", "surroundings"), family="CHEM-TH"),
    ch("CHEM-TH-002", SUBJECT_ID, "chem-thermo", "chem_thermo", 3, "TRUE_FALSE",
       "True or false: breaking bonds always releases energy to the surroundings.",
       "False",
       "Breaking bonds requires energy. Forming bonds can release energy.",
       choices=("True", "False"),
       cues=("break requires", "form releases"), family="CHEM-TH"),
    ch("CHEM-OR-001", SUBJECT_ID, "chem-organic", "chem_organic", 2, "CONCEPT_CHECK",
       "Organic chemistry mainly studies compounds of:",
       "Carbon (often with H, O, N)",
       "Carbon's bonding versatility is the backbone of organic molecules.",
       choices=("Carbon (often with H, O, N)", "Only noble gases", "Only metals", "Only salts of sodium"),
       cues=("carbon", "organic", "H O N"), family="CHEM-OR"),
    ch("CHEM-OR-002", SUBJECT_ID, "chem-organic", "chem_organic", 3, "MATCH",
       "The –OH group in alcohols is called a:",
       "Hydroxyl functional group",
       "Functional groups determine much of the reactivity.",
       choices=("Hydroxyl functional group", "A nucleus", "A photon", "An isotope"),
       cues=("OH", "alcohol", "functional"), family="CHEM-OR"),
    ch("CHEM-EQ-001", SUBJECT_ID, "chem-eq", "chem_eq", 2, "CONCEPT_CHECK",
       "At chemical equilibrium:",
       "Forward and reverse rates are equal (concentrations stay constant)",
       "Reactions still occur, but there is no net change.",
       choices=("Forward and reverse rates are equal (concentrations stay constant)", "All molecules stop moving", "The reaction has not started", "Only products remain"),
       cues=("equal rates", "dynamic", "constant"), family="CHEM-EQ"),
    ch("CHEM-EQ-002", SUBJECT_ID, "chem-eq", "chem_eq", 3, "TRUE_FALSE",
       "True or false: equilibrium means the reaction has stopped completely.",
       "False",
       "It is dynamic: both directions continue at equal rate.",
       choices=("True", "False"),
       cues=("dynamic", "not stopped"), family="CHEM-EQ"),
    ch("CHEM-GAS-001", SUBJECT_ID, "chem-gases", "chem_gases", 2, "CONCEPT_CHECK",
       "If T is held constant, Boyle's law says P and V are:",
       "Inversely related",
       "PV is constant for a fixed amount of ideal gas at constant T.",
       choices=("Inversely related", "Unrelated", "Always equal", "Infinite"),
       cues=("Boyle", "inverse", "PV"), family="CHEM-GAS"),
    ch("CHEM-GAS-002", SUBJECT_ID, "chem-gases", "chem_gases", 3, "NUMERIC",
       "A gas at 2 atm occupies 4 L. At constant T, what volume at 1 atm? (Boyle)",
       "8 L",
       "P1 V1 = P2 V2 → 2×4 = 1×V2 → V2 = 8 L.",
       cues=("Boyle", "PV", "8"), family="CHEM-GAS", representation="numeric"),
    ch("CHEM-PE-001", SUBJECT_ID, "chem-periodic", "chem_periodic", 2, "CONCEPT_CHECK",
       "Atomic radius generally decreases across a period because:",
       "Effective nuclear charge increases, pulling electrons closer",
       "More protons pull the same shell more tightly.",
       choices=("Effective nuclear charge increases, pulling electrons closer", "Atoms gain more neutron planets", "Gravity increases", "Electrons disappear"),
       cues=("effective Z", "period", "smaller"), family="CHEM-PE"),
    ch("CHEM-PE-002", SUBJECT_ID, "chem-periodic", "chem_periodic", 3, "TRUE_FALSE",
       "True or false: noble gases are typically unreactive compared with alkali metals.",
       "True",
       "Filled valence shells make noble gases relatively inert; alkali metals have one loosely held electron.",
       choices=("True", "False"),
       cues=("noble", "unreactive", "alkali"), family="CHEM-PE"),
)
