"""Computer Science catalog: programming, structures, algorithms, OOP, databases."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "computer-science"

TOPICS = (
    TopicSpec("cs-programming", SUBJECT_ID, "Programming Fundamentals", "Variables, control flow, and basic programs.", ("cs_variables", "cs_control_flow"), "CS-PROG-001"),
    TopicSpec("cs-data-structures", SUBJECT_ID, "Data Structures", "How data is organized for efficient access.", ("cs_arrays", "cs_lists", "cs_trees"), "CS-DS-001"),
    TopicSpec("cs-algorithms", SUBJECT_ID, "Algorithms", "Complexity, searching, and sorting.", ("cs_complexity", "cs_search", "cs_sort"), "CS-ALG-001"),
    TopicSpec("cs-oop", SUBJECT_ID, "Object-Oriented Programming", "Objects, classes, and encapsulation.", ("cs_classes",), "CS-OOP-001"),
    TopicSpec("cs-databases", SUBJECT_ID, "Databases", "Tables, keys, and simple queries.", ("cs_relational",), "CS-DB-001"),
)

CONCEPTS = (
    ConceptSpec("cs_variables", "cs-programming", SUBJECT_ID, "Variables and types", "Names that hold values."),
    ConceptSpec("cs_control_flow", "cs-programming", SUBJECT_ID, "Control flow", "Decisions and loops."),
    ConceptSpec("cs_arrays", "cs-data-structures", SUBJECT_ID, "Arrays", "Indexed contiguous collections."),
    ConceptSpec("cs_lists", "cs-data-structures", SUBJECT_ID, "Linked lists", "Nodes connected by pointers."),
    ConceptSpec("cs_trees", "cs-data-structures", SUBJECT_ID, "Trees", "Hierarchical node structures."),
    ConceptSpec("cs_complexity", "cs-algorithms", SUBJECT_ID, "Time complexity", "How runtime grows with input size.", "BEGINNER"),
    ConceptSpec("cs_search", "cs-algorithms", SUBJECT_ID, "Searching", "Finding an item in a collection.", "INTERMEDIATE"),
    ConceptSpec("cs_sort", "cs-algorithms", SUBJECT_ID, "Sorting", "Ordering a collection.", "INTERMEDIATE"),
    ConceptSpec("cs_classes", "cs-oop", SUBJECT_ID, "Classes and objects", "Blueprints for objects."),
    ConceptSpec("cs_relational", "cs-databases", SUBJECT_ID, "Relational model", "Tables, keys, and relations."),
)

O_NLOGN = (("CS-M001", ("always faster", "n log n is always", "better for every n")),)
ARR_LIST = (("CS-M002", ("same as array", "arrays and lists are the same", "no difference")),)
HASH_SORT = (("CS-M003", ("hash table sorts", "hashing sorts")),)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("CS-PROG-001", SUBJECT_ID, "cs-programming", "cs_variables", 1, "CONCEPT_CHECK",
       "A variable is best described as which of the following?",
       "A named location that stores a value",
       "A variable is a named place in memory that holds a value you can read or update.",
       choices=("A named location that stores a value", "A function that always returns 0", "A comment in the code", "A compiler error"),
       cues=("named", "stores", "value"), family="CS-PROG-VAR"),
    ch("CS-PROG-002", SUBJECT_ID, "cs-programming", "cs_variables", 2, "PREDICTION",
       "x starts at 3. After x = x + 2, what is x?",
       "5",
       "The new value is the old value plus 2, so 3 + 2 = 5.",
       cues=("plus", "add", "update"), family="CS-PROG-ASSIGN"),
    ch("CS-PROG-003", SUBJECT_ID, "cs-programming", "cs_control_flow", 2, "SEQUENCE",
       "A loop should run while n is positive, then stop. Which condition belongs in `while (___):`?",
       "n > 0",
       "The loop continues only while the condition is true. n > 0 keeps it running for positive n.",
       choices=("n > 0", "n = 0", "n + 1", "True and False"),
       cues=("while", "positive", "condition")),
    ch("CS-PROG-004", SUBJECT_ID, "cs-programming", "cs_control_flow", 3, "ERROR_ANALYSIS",
       "A student writes `if x = 10:` to test equality. Where did they go wrong?",
       "Used assignment instead of comparison",
       "`=` assigns. Comparison uses `==`. The condition as written would not test equality.",
       choices=("Used assignment instead of comparison", "Forgot a loop", "Used a string", "Divided by zero"),
       cues=("assignment", "comparison", "=="), diagnostic=0.9),
    ch("CS-PROG-005", SUBJECT_ID, "cs-programming", "cs_control_flow", 3, "APPLICATION",
       "You need to print every even number from 2 through 10. Which idea works?",
       "Loop and print when the number is divisible by 2",
       "Iterate the range and keep values with remainder 0 when divided by 2.",
       cues=("loop", "even", "divisible"), strategies=("INCREASE", "MAINTAIN")),
    ch("CS-DS-001", SUBJECT_ID, "cs-data-structures", "cs_arrays", 2, "MULTIPLE_CHOICE",
       "What is the typical time to read the k-th element of an array?",
       "O(1)",
       "Arrays support constant-time index access because the address can be computed directly.",
       choices=("O(1)", "O(n)", "O(n log n)", "O(n²)"),
       cues=("index", "constant", "address")),
    ch("CS-DS-002", SUBJECT_ID, "cs-data-structures", "cs_lists", 3, "COMPARE",
       "What is a key difference between an array and a singly linked list?",
       "Arrays give index access in O(1); linked lists need O(n) to reach the k-th node",
       "Linked lists store nodes by pointer, so you walk from the head. Arrays compute an offset.",
       choices=(
           "Arrays give index access in O(1); linked lists need O(n) to reach the k-th node",
           "They are the same structure with different names",
           "Linked lists are always faster",
           "Arrays cannot store numbers",
       ),
       misconceptions=ARR_LIST, target="CS-M002", cues=("index", "pointer", "walk")),
    ch("CS-DS-003", SUBJECT_ID, "cs-data-structures", "cs_lists", 2, "TRUE_FALSE",
       "True or false: a singly linked list can always access the k-th item as fast as an array.",
       "False",
       "Reaching the k-th node takes a walk from the head, so it is not constant time.",
       choices=("True", "False"),
       misconceptions=ARR_LIST, target="CS-M002", cues=("walk", "not constant")),
    ch("CS-DS-004", SUBJECT_ID, "cs-data-structures", "cs_trees", 3, "CONCEPT_CHECK",
       "In a binary tree, how many children can a node have at most?",
       "2",
       "A binary tree node has at most a left child and a right child.",
       cues=("binary", "two", "left", "right")),
    ch("CS-DS-005", SUBJECT_ID, "cs-data-structures", "cs_trees", 4, "PREDICTION",
       "A binary search tree has root 8, left 3, right 10. Where is 9 inserted?",
       "Left child of 10",
       "9 is greater than 8 so go right, then less than 10 so it becomes the left child of 10.",
       cues=("greater", "right", "less", "left"), strategies=("INCREASE", "MAINTAIN")),
    ch("CS-ALG-001", SUBJECT_ID, "cs-algorithms", "cs_complexity", 2, "MULTIPLE_CHOICE",
       "What is the time complexity of binary search on a sorted array?",
       "O(log n)",
       "Binary search halves the search space each step, so the time grows logarithmically.",
       choices=("O(n)", "O(log n)", "O(n²)", "O(1)"),
       cues=("halve", "log", "sorted"), family="CS-ALG-BINSEARCH"),
    ch("CS-ALG-002", SUBJECT_ID, "cs-algorithms", "cs_complexity", 2, "TRUE_FALSE",
       "True or false: O(n log n) is faster than O(n) for every input size n.",
       "False",
       "Big-O describes growth. For small n, constants matter. Linear can beat n log n on tiny inputs, and n log n grows faster than n.",
       choices=("True", "False"),
       misconceptions=O_NLOGN, target="CS-M001", cues=("growth", "constants", "small n"), family="CS-ALG-BIGO"),
    ch("CS-ALG-003", SUBJECT_ID, "cs-algorithms", "cs_search", 3, "PREDICTION",
       "Binary search looks at a sorted list [2, 5, 8, 11, 14] for 11. What is the first midpoint value compared?",
       "8",
       "The middle index of five items is 2, whose value is 8.",
       cues=("middle", "midpoint", "sorted"), family="CS-ALG-BINSEARCH"),
    ch("CS-ALG-004", SUBJECT_ID, "cs-algorithms", "cs_sort", 3, "MULTIPLE_CHOICE",
       "Which algorithm has O(n log n) average time?",
       "Mergesort",
       "Mergesort splits and merges in O(n log n) in the average and worst case.",
       choices=("Bubblesort", "Mergesort", "Linear search", "Binary search"),
       cues=("merge", "split", "n log n"), family="CS-ALG-SORT"),
    ch("CS-ALG-005", SUBJECT_ID, "cs-algorithms", "cs_sort", 3, "ERROR_ANALYSIS",
       "A student says bubblesort is O(n log n) because it uses nested loops. Where did they go wrong?",
       "Nested loops here compare about n² pairs, so bubblesort is O(n²)",
       "Two nested loops over the list produce quadratic comparisons, not n log n.",
       choices=(
           "Nested loops here compare about n² pairs, so bubblesort is O(n²)",
           "Bubblesort does not use loops",
           "All sorts are O(1)",
           "They forgot to reverse the array",
       ),
       cues=("nested", "quadratic", "n²"), family="CS-ALG-SORT"),
    ch("CS-ALG-006", SUBJECT_ID, "cs-algorithms", "cs_complexity", 4, "TRANSFER",
       "You need the closest match in a huge sorted timestamp list. Which approach scales best?",
       "Binary search",
       "Sorted data lets binary search discard half the remaining timestamps each step.",
       cues=("sorted", "binary", "half"), strategies=("INCREASE", "MAINTAIN"), family="CS-ALG-BINSEARCH"),
    ch("CS-ALG-007", SUBJECT_ID, "cs-algorithms", "cs_search", 3, "DIAGNOSTIC",
       "If an array is unsorted, can binary search still guarantee O(log n) lookups? Why?",
       "No",
       "Binary search relies on order. Without sorted order, discarding a half is not valid.",
       cues=("unsorted", "order", "cannot discard"), diagnostic=0.92, family="CS-ALG-BINSEARCH"),
    ch("CS-ALG-008", SUBJECT_ID, "cs-algorithms", "cs_complexity", 2, "REMEDIATION",
       "O(n) counts work that grows linearly. If n doubles, about how much does the work grow?",
       "It about doubles",
       "Linear time means work scales with n. Doubling n roughly doubles the work.",
       misconceptions=O_NLOGN, target="CS-M001", cues=("linear", "doubles", "scales"),
       strategies=("REMEDIATE", "DECREASE", "PROBE"), family="CS-ALG-BIGO"),
    ch("CS-ALG-009", SUBJECT_ID, "cs-algorithms", "cs_sort", 5, "APPLICATION",
       "A log of 10 million already-sorted events needs a few new events merged in order. What is a sound idea?",
       "Insert with binary search or merge like mergesort",
       "The existing order is an asset. Binary insertion or a linear merge preserves order more cheaply than sorting from scratch.",
       cues=("sorted", "merge", "insert"), strategies=("INCREASE",), family="CS-ALG-SORT"),
    ch("CS-ALG-010", SUBJECT_ID, "cs-algorithms", "cs_search", 1, "CONCEPT_CHECK",
       "Linear search on n items takes time proportional to what, in the worst case?",
       "n",
       "In the worst case you may inspect every item, so the work is proportional to n.",
       choices=("n", "log n", "1", "n²"),
       cues=("every", "worst", "linear"), family="CS-ALG-LINEAR"),
    ch("CS-OOP-001", SUBJECT_ID, "cs-oop", "cs_classes", 2, "CONCEPT_CHECK",
       "A class is best described as:",
       "A blueprint for creating objects",
       "A class defines fields and methods. Objects are instances built from that blueprint.",
       choices=("A blueprint for creating objects", "A running program", "A database table", "A compiler flag"),
       cues=("blueprint", "instance", "object")),
    ch("CS-OOP-002", SUBJECT_ID, "cs-oop", "cs_classes", 3, "COMPARE",
       "What is a difference between a class and an object?",
       "A class is the definition; an object is a particular instance",
       "The class is the type. Each object has its own state created from that type.",
       cues=("definition", "instance", "state")),
    ch("CS-OOP-003", SUBJECT_ID, "cs-oop", "cs_classes", 3, "PREDICTION",
       "class Counter has value 0. After c.inc(); c.inc(); what is c.value if inc adds 1?",
       "2",
       "Each inc adds one to that object's value, so two calls yield 2.",
       cues=("instance", "adds", "object")),
    ch("CS-OOP-004", SUBJECT_ID, "cs-oop", "cs_classes", 4, "ERROR_ANALYSIS",
       "A student puts all program data in one global variable 'to keep OOP simple'. What is the issue?",
       "That skips encapsulation: objects should hold their own state",
       "OOP groups state with the operations that use it. A single global undoes that boundary.",
       cues=("encapsulation", "state", "global"), strategies=("INCREASE", "PROBE")),
    ch("CS-DB-001", SUBJECT_ID, "cs-databases", "cs_relational", 2, "CONCEPT_CHECK",
       "In a relational database, a primary key is:",
       "A unique identifier for each row",
       "The primary key uniquely identifies a tuple/row so other tables can reference it.",
       choices=("A unique identifier for each row", "A backup of the table", "A sorting algorithm", "A UI theme"),
       cues=("unique", "row", "identifier")),
    ch("CS-DB-002", SUBJECT_ID, "cs-databases", "cs_relational", 3, "APPLICATION",
       "Students and Courses: each enrollment links one student to one course. What kind of relationship is that?",
       "Many-to-many, usually via an enrollment table",
       "A student can take many courses and a course has many students, so a join table holds enrollments.",
       cues=("many-to-many", "join", "enrollment")),
    ch("CS-DB-003", SUBJECT_ID, "cs-databases", "cs_relational", 3, "PREDICTION",
       "SELECT name FROM students WHERE id = 7; returns how many rows if id is a primary key and 7 exists?",
       "1",
       "A primary key is unique, so at most one row matches that id.",
       cues=("primary key", "unique", "one row")),
    ch("CS-DB-004", SUBJECT_ID, "cs-databases", "cs_relational", 2, "TRUE_FALSE",
       "True or false: two rows in the same table may share the same primary key value.",
       "False",
       "Primary keys must be unique. Duplicate key values would not identify a single row.",
       choices=("True", "False"),
       cues=("unique", "cannot share")),
)
