"""Mathematics catalog. Algebra and fractions wrap the frozen Phase 3 bank."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "mathematics"

TOPICS = (
    TopicSpec("math-arithmetic", SUBJECT_ID, "Arithmetic", "Whole-number operations and number sense.", ("math_arithmetic",), "MATH-AR-001"),
    TopicSpec("algebra", SUBJECT_ID, "Algebra", "Solve equations and reason about expressions.", ("basic_algebra",), "ALG-D-001", legacy=True),
    TopicSpec("fractions", SUBJECT_ID, "Fractions", "Add, subtract, and reason about parts of a whole.", ("fractions",), "FR-D-001", legacy=True),
    TopicSpec("math-geometry", SUBJECT_ID, "Geometry", "Shapes, angles, and area.", ("math_geometry",), "MATH-GEO-001"),
    TopicSpec("math-trigonometry", SUBJECT_ID, "Trigonometry", "Right triangles and basic trig ratios.", ("math_trig",), "MATH-TRIG-001"),
)

CONCEPTS = (
    ConceptSpec("math_arithmetic", "math-arithmetic", SUBJECT_ID, "Arithmetic operations", "Add, subtract, multiply, divide."),
    ConceptSpec("basic_algebra", "algebra", SUBJECT_ID, "Linear equations", "Isolate a variable using inverse operations."),
    ConceptSpec("fractions", "fractions", SUBJECT_ID, "Fraction operations", "Equivalent fractions and common denominators."),
    ConceptSpec("math_geometry", "math-geometry", SUBJECT_ID, "Plane geometry", "Angles, triangles, and area."),
    ConceptSpec("math_trig", "math-trigonometry", SUBJECT_ID, "Right-triangle trigonometry", "Sine, cosine, and tangent as ratios."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("MATH-AR-001", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 1, "DIRECT",
       "What is 17 + 8?", "25",
       "Add the ones: 7 + 8 = 15, write 5 and carry 1. 1 + 1 = 2, so 25.",
       cues=("add", "sum", "carry"), family="MATH-AR-ADD"),
    ch("MATH-AR-002", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 2, "DIRECT",
       "What is 9 × 7?", "63",
       "Nine sevens are 63.",
       cues=("multiply", "product", "times"), family="MATH-AR-MUL"),
    ch("MATH-AR-003", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 2, "ERROR_ANALYSIS",
       "A student computes 15 − 7 as 12 because they subtracted 5 − 7 by flipping the digits. Where did they go wrong?",
       "They reversed the ones digits instead of regrouping",
       "15 − 7 needs regrouping: 15 is 1 ten and 5 ones, so borrow to make 15 ones minus 7.",
       cues=("regroup", "borrow", "ones"), family="MATH-AR-SUB"),
    ch("MATH-AR-004", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 3, "APPLICATION",
       "A box holds 6 rows of 8 bottles. How many bottles are there?",
       "48",
       "Rows times bottles per row: 6 × 8 = 48.",
       cues=("multiply", "rows", "groups"), family="MATH-AR-MUL"),
    ch("MATH-AR-005", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 3, "TRANSFER",
       "You split 36 stickers equally among 4 friends. How many does each get?",
       "9",
       "Equal sharing is division: 36 ÷ 4 = 9.",
       cues=("divide", "equal", "share"), family="MATH-AR-DIV"),
    ch("MATH-GEO-001", SUBJECT_ID, "math-geometry", "math_geometry", 2, "CONCEPT_CHECK",
       "The sum of interior angles in a triangle is:",
       "180 degrees",
       "Any Euclidean triangle's interior angles add to 180°.",
       choices=("90 degrees", "180 degrees", "360 degrees", "45 degrees"),
       cues=("triangle", "180", "interior")),
    ch("MATH-GEO-002", SUBJECT_ID, "math-geometry", "math_geometry", 2, "DIRECT",
       "A rectangle is 5 by 8. What is its area?",
       "40",
       "Area of a rectangle is length times width: 5 × 8 = 40.",
       cues=("area", "length", "width")),
    ch("MATH-GEO-003", SUBJECT_ID, "math-geometry", "math_geometry", 3, "APPLICATION",
       "A right triangle has legs 3 and 4. What is the hypotenuse?",
       "5",
       "Pythagoras: 3² + 4² = 9 + 16 = 25, so the hypotenuse is 5.",
       cues=("Pythagoras", "legs", "hypotenuse")),
    ch("MATH-GEO-004", SUBJECT_ID, "math-geometry", "math_geometry", 3, "ERROR_ANALYSIS",
       "A student says a square with side 4 has perimeter 16 and area 16, so perimeter always equals area. What's wrong?",
       "Those numbers match only for this side length; the units and formulas differ",
       "Perimeter is 4s; area is s². They can share a number by coincidence, but they measure different things.",
       cues=("perimeter", "area", "different")),
    ch("MATH-GEO-005", SUBJECT_ID, "math-geometry", "math_geometry", 4, "TRANSFER",
       "A circular garden has radius 7. Which expression is its area (use π)?",
       "49π",
       "Area = πr² = π·49 = 49π.",
       cues=("pi", "radius squared", "area"), strategies=("INCREASE", "MAINTAIN")),
    ch("MATH-GEO-006", SUBJECT_ID, "math-geometry", "math_geometry", 1, "TRUE_FALSE",
       "True or false: a square is a special rectangle.",
       "True",
       "A square has four right angles and opposite sides equal, so it meets the definition of a rectangle.",
       choices=("True", "False"),
       cues=("right angles", "rectangle", "square")),
    ch("MATH-TRIG-001", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "CONCEPT_CHECK",
       "In a right triangle, sin θ is which ratio?",
       "opposite / hypotenuse",
       "Sine is the opposite side over the hypotenuse.",
       choices=("opposite / hypotenuse", "adjacent / hypotenuse", "opposite / adjacent", "hypotenuse / opposite"),
       cues=("opposite", "hypotenuse", "sine")),
    ch("MATH-TRIG-002", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "COMPARE",
       "How do sine and cosine differ for an acute angle in a right triangle?",
       "Sine uses opposite; cosine uses adjacent (both over hypotenuse)",
       "Both divide by the hypotenuse. Sine takes the opposite side; cosine takes the adjacent side.",
       cues=("opposite", "adjacent", "hypotenuse")),
    ch("MATH-TRIG-003", SUBJECT_ID, "math-trigonometry", "math_trig", 3, "DIRECT",
       "A right triangle has opposite = 3 and hypotenuse = 5. What is sin θ?",
       "3/5",
       "sin θ = opposite / hypotenuse = 3/5.",
       cues=("opposite", "hypotenuse", "3/5")),
    ch("MATH-TRIG-004", SUBJECT_ID, "math-trigonometry", "math_trig", 3, "PREDICTION",
       "If cos θ = 4/5 in a right triangle, what is the adjacent side if the hypotenuse is 10?",
       "8",
       "adjacent / 10 = 4/5, so adjacent = 8.",
       cues=("adjacent", "cosine", "scale")),
    ch("MATH-TRIG-005", SUBJECT_ID, "math-trigonometry", "math_trig", 4, "APPLICATION",
       "A 20 m ladder leans so that sin θ = 0.6, with θ at the ground. About how high is the top on the wall?",
       "12 m",
       "sin θ = height / 20 = 0.6, so height = 12 m.",
       cues=("sine", "height", "ladder"), strategies=("INCREASE", "MAINTAIN")),
    ch("MATH-TRIG-006", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "TRUE_FALSE",
       "True or false: tan θ = opposite / adjacent.",
       "True",
       "Tangent is the ratio of the opposite side to the adjacent side.",
       choices=("True", "False"),
       cues=("tangent", "opposite", "adjacent")),
)
