"""Mathematics catalog. Algebra and fractions wrap the frozen Phase 3 bank."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "mathematics"

TOPICS = (
    TopicSpec("math-arithmetic", SUBJECT_ID, "Arithmetic", "Whole-number operations and number sense.", ("math_arithmetic",), "MATH-AR-001"),
    TopicSpec("algebra", SUBJECT_ID, "Algebra", "Solve equations and reason about expressions.", ("basic_algebra",), "ALG-D-001", legacy=True),
    TopicSpec("fractions", SUBJECT_ID, "Fractions", "Add, subtract, and reason about parts of a whole.", ("fractions",), "FR-D-001", legacy=True),
    TopicSpec("math-geometry", SUBJECT_ID, "Geometry", "Shapes, angles, and area.", ("math_geometry",), "MATH-GEO-001"),
    TopicSpec("math-trigonometry", SUBJECT_ID, "Trigonometry", "Right triangles and basic trig ratios.", ("math_trig",), "MATH-TRIG-001"),
    TopicSpec("math-percent", SUBJECT_ID, "Percentages", "Parts of 100 and proportional change.", ("math_percent",), "MATH-PCT-001"),
    TopicSpec("math-stats", SUBJECT_ID, "Statistics", "Averages, spread, and simple chance.", ("math_stats",), "MATH-ST-001"),
    TopicSpec("math-functions", SUBJECT_ID, "Functions", "Inputs, outputs, and graphs.", ("math_functions",), "MATH-FN-001"),
    TopicSpec("math-exponents", SUBJECT_ID, "Exponents", "Powers, roots, and scientific notation.", ("math_exp",), "MATH-EX-001"),
    TopicSpec("math-inequalities", SUBJECT_ID, "Inequalities", "Comparing quantities and solution sets.", ("math_ineq",), "MATH-IN-001"),
)

CONCEPTS = (
    ConceptSpec("math_arithmetic", "math-arithmetic", SUBJECT_ID, "Arithmetic operations", "Add, subtract, multiply, divide."),
    ConceptSpec("basic_algebra", "algebra", SUBJECT_ID, "Linear equations", "Isolate a variable using inverse operations."),
    ConceptSpec("fractions", "fractions", SUBJECT_ID, "Fraction operations", "Equivalent fractions and common denominators."),
    ConceptSpec("math_geometry", "math-geometry", SUBJECT_ID, "Plane geometry", "Angles, triangles, and area."),
    ConceptSpec("math_trig", "math-trigonometry", SUBJECT_ID, "Right-triangle trigonometry", "Sine, cosine, and tangent as ratios."),
    ConceptSpec("math_percent", "math-percent", SUBJECT_ID, "Percentages", "A percent is a part of 100."),
    ConceptSpec("math_stats", "math-stats", SUBJECT_ID, "Descriptive statistics", "Mean, median, and simple probability."),
    ConceptSpec("math_functions", "math-functions", SUBJECT_ID, "Functions", "A rule that assigns each input one output."),
    ConceptSpec("math_exp", "math-exponents", SUBJECT_ID, "Exponents", "Repeated multiplication and powers of ten."),
    ConceptSpec("math_ineq", "math-inequalities", SUBJECT_ID, "Inequalities", "Compare values with <, >, ≤, ≥."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("MATH-AR-001", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 1, "DIRECT",
       "What is 17 + 8?", "25",
       "Add the ones: 7 + 8 = 15, write 5 and carry 1. 1 + 1 = 2, so 25.",
       cues=("add", "sum", "carry"), family="MATH-AR-ADD"),
    ch("MATH-AR-002", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 2, "DIRECT",
       "What is 9 × 7?", "63",
       "Nine sevens are 63.",
       cues=("multiply", "product", "times"), family="MATH-AR-MUL"),
    ch("MATH-AR-003", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 2, "ERROR_ANALYSIS",
       "A student computes 15 − 7 as 12 because they subtracted 5 − 7 by flipping the digits. Where did they go wrong?",
       "They reversed the ones digits instead of regrouping",
       "15 − 7 needs regrouping: 15 is 1 ten and 5 ones, so borrow to make 15 ones minus 7.",
       cues=("regroup", "borrow", "ones"), family="MATH-AR-SUB"),
    ch("MATH-AR-004", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 3, "APPLICATION",
       "A box holds 6 rows of 8 bottles. How many bottles are there?",
       "48",
       "Rows times bottles per row: 6 × 8 = 48.",
       cues=("multiply", "rows", "groups"), family="MATH-AR-MUL"),
    ch("MATH-AR-005", SUBJECT_ID, "math-arithmetic", "math_arithmetic", 3, "TRANSFER",
       "You split 36 stickers equally among 4 friends. How many does each get?",
       "9",
       "Equal sharing is division: 36 ÷ 4 = 9.",
       cues=("divide", "equal", "share"), family="MATH-AR-DIV"),
    ch("MATH-GEO-001", SUBJECT_ID, "math-geometry", "math_geometry", 2, "CONCEPT_CHECK",
       "The sum of interior angles in a triangle is:",
       "180 degrees",
       "Any Euclidean triangle's interior angles add to 180°.",
       choices=("90 degrees", "180 degrees", "360 degrees", "45 degrees"),
       cues=("triangle", "180", "interior")),
    ch("MATH-GEO-002", SUBJECT_ID, "math-geometry", "math_geometry", 2, "DIRECT",
       "A rectangle is 5 by 8. What is its area?",
       "40",
       "Area of a rectangle is length times width: 5 × 8 = 40.",
       cues=("area", "length", "width")),
    ch("MATH-GEO-003", SUBJECT_ID, "math-geometry", "math_geometry", 3, "APPLICATION",
       "A right triangle has legs 3 and 4. What is the hypotenuse?",
       "5",
       "Pythagoras: 3² + 4² = 9 + 16 = 25, so the hypotenuse is 5.",
       cues=("Pythagoras", "legs", "hypotenuse")),
    ch("MATH-GEO-004", SUBJECT_ID, "math-geometry", "math_geometry", 3, "ERROR_ANALYSIS",
       "A student says a square with side 4 has perimeter 16 and area 16, so perimeter always equals area. What's wrong?",
       "Those numbers match only for this side length; the units and formulas differ",
       "Perimeter is 4s; area is s². They can share a number by coincidence, but they measure different things.",
       cues=("perimeter", "area", "different")),
    ch("MATH-GEO-005", SUBJECT_ID, "math-geometry", "math_geometry", 4, "TRANSFER",
       "A circular garden has radius 7. Which expression is its area (use π)?",
       "49π",
       "Area = πr² = π·49 = 49π.",
       cues=("pi", "radius squared", "area"), strategies=("INCREASE", "MAINTAIN")),
    ch("MATH-GEO-006", SUBJECT_ID, "math-geometry", "math_geometry", 1, "TRUE_FALSE",
       "True or false: a square is a special rectangle.",
       "True",
       "A square has four right angles and opposite sides equal, so it meets the definition of a rectangle.",
       choices=("True", "False"),
       cues=("right angles", "rectangle", "square")),
    ch("MATH-TRIG-001", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "CONCEPT_CHECK",
       "In a right triangle, sin θ is which ratio?",
       "opposite / hypotenuse",
       "Sine is the opposite side over the hypotenuse.",
       choices=("opposite / hypotenuse", "adjacent / hypotenuse", "opposite / adjacent", "hypotenuse / opposite"),
       cues=("opposite", "hypotenuse", "sine")),
    ch("MATH-TRIG-002", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "COMPARE",
       "How do sine and cosine differ for an acute angle in a right triangle?",
       "Sine uses opposite; cosine uses adjacent (both over hypotenuse)",
       "Both divide by the hypotenuse. Sine takes the opposite side; cosine takes the adjacent side.",
       cues=("opposite", "adjacent", "hypotenuse")),
    ch("MATH-TRIG-003", SUBJECT_ID, "math-trigonometry", "math_trig", 3, "DIRECT",
       "A right triangle has opposite = 3 and hypotenuse = 5. What is sin θ?",
       "3/5",
       "sin θ = opposite / hypotenuse = 3/5.",
       cues=("opposite", "hypotenuse", "3/5")),
    ch("MATH-TRIG-004", SUBJECT_ID, "math-trigonometry", "math_trig", 3, "PREDICTION",
       "If cos θ = 4/5 in a right triangle, what is the adjacent side if the hypotenuse is 10?",
       "8",
       "adjacent / 10 = 4/5, so adjacent = 8.",
       cues=("adjacent", "cosine", "scale")),
    ch("MATH-TRIG-005", SUBJECT_ID, "math-trigonometry", "math_trig", 4, "APPLICATION",
       "A 20 m ladder leans so that sin θ = 0.6, with θ at the ground. About how high is the top on the wall?",
       "12 m",
       "sin θ = height / 20 = 0.6, so height = 12 m.",
       cues=("sine", "height", "ladder"), strategies=("INCREASE", "MAINTAIN")),
    ch("MATH-TRIG-006", SUBJECT_ID, "math-trigonometry", "math_trig", 2, "TRUE_FALSE",
       "True or false: tan θ = opposite / adjacent.",
       "True",
       "Tangent is the ratio of the opposite side to the adjacent side.",
       choices=("True", "False"),
       cues=("tangent", "opposite", "adjacent")),
    ch("MATH-PCT-001", SUBJECT_ID, "math-percent", "math_percent", 2, "NUMERIC",
       "What is 25% of 80?", "20",
       "25% is 1/4, and 80 ÷ 4 = 20.",
       cues=("percent", "quarter", "20"), family="MATH-PCT", representation="numeric"),
    ch("MATH-PCT-002", SUBJECT_ID, "math-percent", "math_percent", 2, "MULTIPLE_CHOICE",
       "A price rises from $40 to $50. What is the percent increase?",
       "25%",
       "Increase is $10. 10/40 = 0.25 = 25%.",
       choices=("10%", "20%", "25%", "50%"),
       cues=("increase", "over original", "25"), family="MATH-PCT", representation="verbal"),
    ch("MATH-PCT-003", SUBJECT_ID, "math-percent", "math_percent", 3, "ESTIMATION",
       "About what is 19% of 200?",
       "40",
       "19% is near 20%. 20% of 200 is 40.",
       cues=("about 20%", "200", "40"), family="MATH-PCT", representation="numeric"),
    ch("MATH-ST-001", SUBJECT_ID, "math-stats", "math_stats", 2, "NUMERIC",
       "The mean of 2, 4, and 6 is:", "4",
       "Add and divide by 3: 12/3 = 4.",
       cues=("mean", "average", "divide"), family="MATH-ST", representation="numeric"),
    ch("MATH-ST-002", SUBJECT_ID, "math-stats", "math_stats", 2, "MATCH",
       "Match: the middle value of an ordered list is called the:",
       "Median",
       "Median is the middle once the data are ordered.",
       choices=("Mean", "Median", "Range", "Mode only if unique"),
       cues=("middle", "ordered", "median"), family="MATH-ST", representation="verbal"),
    ch("MATH-ST-003", SUBJECT_ID, "math-stats", "math_stats", 3, "SCENARIO",
       "A fair six-sided die is rolled. Probability of an even number?",
       "1/2",
       "Even faces: 2, 4, 6 — three of six equally likely outcomes.",
       cues=("even", "3 of 6", "half"), family="MATH-ST", representation="scenario"),
    ch("MATH-FN-001", SUBJECT_ID, "math-functions", "math_functions", 2, "CONCEPT_CHECK",
       "A function assigns to each allowed input:",
       "Exactly one output",
       "Each input in the domain maps to one output.",
       choices=("Exactly one output", "Two outputs always", "No outputs", "A random set"),
       cues=("one output", "input", "map"), family="MATH-FN"),
    ch("MATH-FN-002", SUBJECT_ID, "math-functions", "math_functions", 3, "DIAGRAM",
       "On a graph, f(x) = 2x + 1 at x = 3 is which point?",
       "(3, 7)",
       "f(3) = 6 + 1 = 7, so the point is (3, 7).",
       choices=("(3, 7)", "(7, 3)", "(3, 5)", "(2, 3)"),
       cues=("substitute", "2x+1", "point"), family="MATH-FN", representation="visual"),
    ch("MATH-FN-003", SUBJECT_ID, "math-functions", "math_functions", 2, "SHORT_ANSWER",
       "If f(x) = x + 1, what is f(4)?",
       "5",
       "Replace x with 4: 4 + 1 = 5.",
       cues=("input", "output", "5"), family="MATH-FN", representation="symbolic"),
    ch("MATH-EX-001", SUBJECT_ID, "math-exponents", "math_exp", 2, "NUMERIC",
       "What is 2³?", "8",
       "2×2×2 = 8.",
       cues=("power", "repeated multiply", "8"), family="MATH-EX", representation="numeric"),
    ch("MATH-EX-002", SUBJECT_ID, "math-exponents", "math_exp", 3, "TRUE_FALSE",
       "True or false: 10³ = 1000.",
       "True",
       "A thousand is 10×10×10.",
       choices=("True", "False"),
       cues=("powers of ten", "1000"), family="MATH-EX"),
    ch("MATH-IN-001", SUBJECT_ID, "math-inequalities", "math_ineq", 2, "TRUE_FALSE",
       "True or false: 3 < 5.",
       "True",
       "3 is to the left of 5 on the number line.",
       choices=("True", "False"),
       cues=("less than", "number line"), family="MATH-IN"),
    ch("MATH-IN-002", SUBJECT_ID, "math-inequalities", "math_ineq", 3, "DIRECT",
       "Solve: x + 4 > 10. Which describes the solutions?",
       "x > 6",
       "Subtract 4: x > 6.",
       choices=("x > 6", "x < 6", "x = 6", "x > 14"),
       cues=("subtract", "same direction", "6"), family="MATH-IN", representation="symbolic"),
)
