"""Physics catalog: mechanics through waves."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "physics"

TOPICS = (
    TopicSpec("phys-mechanics", SUBJECT_ID, "Mechanics", "Motion described by kinematics.", ("phys_motion",), "PHYS-MECH-001"),
    TopicSpec("phys-forces", SUBJECT_ID, "Forces", "Newton's laws and net force.", ("phys_newton",), "PHYS-FOR-001"),
    TopicSpec("phys-energy", SUBJECT_ID, "Energy", "Work, kinetic, and potential energy.", ("phys_energy",), "PHYS-EN-001"),
    TopicSpec("phys-momentum", SUBJECT_ID, "Momentum", "p = mv and conservation in collisions.", ("phys_momentum",), "PHYS-MOM-001"),
    TopicSpec("phys-electricity", SUBJECT_ID, "Electricity", "Charge, current, and simple circuits.", ("phys_electric",), "PHYS-EL-001"),
    TopicSpec("phys-waves", SUBJECT_ID, "Waves", "Wavelength, frequency, and speed.", ("phys_waves",), "PHYS-WV-001"),
)

CONCEPTS = (
    ConceptSpec("phys_motion", "phys-mechanics", SUBJECT_ID, "Kinematics", "Displacement, velocity, acceleration."),
    ConceptSpec("phys_newton", "phys-forces", SUBJECT_ID, "Newton's laws", "Net force and acceleration."),
    ConceptSpec("phys_energy", "phys-energy", SUBJECT_ID, "Mechanical energy", "Work and energy transfer."),
    ConceptSpec("phys_momentum", "phys-momentum", SUBJECT_ID, "Momentum", "Mass times velocity."),
    ConceptSpec("phys_electric", "phys-electricity", SUBJECT_ID, "Electric circuits", "Current, voltage, resistance."),
    ConceptSpec("phys_waves", "phys-waves", SUBJECT_ID, "Wave basics", "v = fλ."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("PHYS-MECH-001", SUBJECT_ID, "phys-mechanics", "phys_motion", 2, "CONCEPT_CHECK",
       "If velocity is constant, acceleration is:",
       "Zero",
       "Acceleration is the rate of change of velocity. Constant velocity means zero acceleration.",
       choices=("Zero", "Equal to velocity", "Infinite", "Always 9.8 m/s²"),
       cues=("constant velocity", "zero", "rate of change")),
    ch("PHYS-MECH-002", SUBJECT_ID, "phys-mechanics", "phys_motion", 3, "DIRECT",
       "A car goes from 0 to 20 m/s in 5 s at constant acceleration. What is that acceleration?",
       "4 m/s²",
       "a = Δv/Δt = 20/5 = 4 m/s².",
       cues=("delta v", "time", "acceleration")),
    ch("PHYS-MECH-003", SUBJECT_ID, "phys-mechanics", "phys_motion", 3, "PREDICTION",
       "An object is thrown straight up. At the highest point, its instantaneous speed is:",
       "0",
       "It stops for an instant before falling. Acceleration is still downward.",
       cues=("highest", "zero speed", "still accelerating")),
    ch("PHYS-FOR-001", SUBJECT_ID, "phys-forces", "phys_newton", 2, "MULTIPLE_CHOICE",
       "Newton's second law is:",
       "F_net = ma",
       "Net force equals mass times acceleration.",
       choices=("F_net = ma", "F = mv", "F = m/a", "F = a/m"),
       cues=("net force", "mass", "acceleration")),
    ch("PHYS-FOR-002", SUBJECT_ID, "phys-forces", "phys_newton", 3, "APPLICATION",
       "A 2 kg box is pulled with 10 N east and 4 N west. What is the magnitude of acceleration?",
       "3 m/s²",
       "F_net = 6 N east. a = F/m = 6/2 = 3 m/s².",
       cues=("net", "subtract", "F/m")),
    ch("PHYS-FOR-003", SUBJECT_ID, "phys-forces", "phys_newton", 3, "TRUE_FALSE",
       "True or false: if an object moves at constant speed in a straight line, the net force is zero.",
       "True",
       "Constant velocity means a = 0, so F_net = 0 by Newton's second law.",
       choices=("True", "False"),
       cues=("constant velocity", "net force zero")),
    ch("PHYS-EN-001", SUBJECT_ID, "phys-energy", "phys_energy", 2, "CONCEPT_CHECK",
       "Kinetic energy of a mass m at speed v is:",
       "½mv²",
       "KE = (1/2) m v².",
       choices=("½mv²", "mv", "mgh only", "½m/v"),
       cues=("half", "mass", "speed squared")),
    ch("PHYS-EN-002", SUBJECT_ID, "phys-energy", "phys_energy", 3, "DIRECT",
       "A 2 kg object sits 5 m above the ground. Taking g = 10 m/s², what is its gravitational potential energy?",
       "100 J",
       "PE = mgh = 2·10·5 = 100 J.",
       cues=("mgh", "height", "potential")),
    ch("PHYS-EN-003", SUBJECT_ID, "phys-energy", "phys_energy", 4, "TRANSFER",
       "A roller coaster drops, converting 2000 J of PE into KE (ignore friction). If mass is 100 kg, what speed does it reach from rest? (KE = ½mv²)",
       "about 6.3 m/s",
       "½·100·v² = 2000 → v² = 40 → v ≈ 6.3 m/s.",
       cues=("conservation", "½mv²", "sqrt"), strategies=("INCREASE", "MAINTAIN")),
    ch("PHYS-MOM-001", SUBJECT_ID, "phys-momentum", "phys_momentum", 2, "CONCEPT_CHECK",
       "Momentum is defined as:",
       "p = mv",
       "Linear momentum is mass times velocity, a vector.",
       choices=("p = mv", "p = ma", "p = ½mv²", "p = mgh"),
       cues=("mass", "velocity", "vector")),
    ch("PHYS-MOM-002", SUBJECT_ID, "phys-momentum", "phys_momentum", 3, "APPLICATION",
       "Two ice skaters push apart. One (50 kg) moves at 2 m/s left. The other is 50 kg. What is their speed?",
       "2 m/s right",
       "Total momentum starts at 0. Equal masses imply equal-and-opposite velocities.",
       cues=("conservation", "opposite", "zero total")),
    ch("PHYS-MOM-003", SUBJECT_ID, "phys-momentum", "phys_momentum", 3, "ERROR_ANALYSIS",
       "A student says a parked truck has more momentum than a moving bicycle because it is heavier. What's missing?",
       "The truck's velocity is zero, so its momentum is zero",
       "Momentum needs velocity. At rest, p = 0 regardless of mass.",
       cues=("at rest", "velocity zero", "p=mv")),
    ch("PHYS-EL-001", SUBJECT_ID, "phys-electricity", "phys_electric", 2, "CONCEPT_CHECK",
       "Ohm's law is:",
       "V = IR",
       "Voltage equals current times resistance in an ohmic resistor.",
       choices=("V = IR", "P = mv", "F = ma", "V = I/R"),
       cues=("voltage", "current", "resistance")),
    ch("PHYS-EL-002", SUBJECT_ID, "phys-electricity", "phys_electric", 3, "DIRECT",
       "A 12 V battery drives 2 A through a resistor. What is the resistance?",
       "6 Ω",
       "R = V/I = 12/2 = 6 ohms.",
       cues=("V/I", "ohms")),
    ch("PHYS-EL-003", SUBJECT_ID, "phys-electricity", "phys_electric", 3, "COMPARE",
       "In a series circuit, what is the same through each resistor?",
       "Current",
       "Series means one path, so the same current flows through each component.",
       cues=("series", "one path", "current")),
    ch("PHYS-WV-001", SUBJECT_ID, "phys-waves", "phys_waves", 2, "DIRECT",
       "A wave has frequency 50 Hz and wavelength 2 m. What is its speed?",
       "100 m/s",
       "v = fλ = 50 × 2 = 100 m/s.",
       cues=("v=fλ", "frequency", "wavelength")),
    ch("PHYS-WV-002", SUBJECT_ID, "phys-waves", "phys_waves", 3, "TRUE_FALSE",
       "True or false: a higher-frequency sound in the same medium has a shorter wavelength.",
       "True",
       "If v is fixed, fλ is constant, so higher f means smaller λ.",
       choices=("True", "False"),
       cues=("v constant", "inversely", "wavelength")),
    ch("PHYS-WV-003", SUBJECT_ID, "phys-waves", "phys_waves", 3, "APPLICATION",
       "Radio waves travel at 3×10⁸ m/s. A station broadcasts at 1×10⁸ Hz. What is the wavelength?",
       "3 m",
       "λ = v/f = 3×10⁸ / 1×10⁸ = 3 m.",
       cues=("v/f", "radio", "wavelength")),
)
