"""Quantum computing / quantum physics beginner–advanced catalog."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "quantum"

Q_M001 = ("Q-M001", ("both 0 and 1", "observe both", "simultaneously observing", "see 0 and 1 at once"))
Q_M002 = ("Q-M002", ("reveals both", "see both components", "measurement shows both"))
Q_M003 = ("Q-M003", ("faster bit", "faster classical", "just a faster"))
Q_M004 = ("Q-M004", ("faster than light", "ftl", "instant communication", "instant message"))
Q_M005 = ("Q-M005", ("every problem", "always faster", "faster for every"))
Q_M006 = ("Q-M006", ("randomly chooses", "coin flip gate", "hadamard picks"))
Q_M007 = ("Q-M007", ("transports matter", "moves the particle", "physically transports"))
Q_M008 = ("Q-M008", ("reverse measurement", "undo measurement", "measurement reversed"))

TOPICS = (
    TopicSpec("quantum-qubits", SUBJECT_ID, "Qubits & Measurement", "Bits vs qubits, superposition, and measurement.", ("q_qubits", "q_superposition", "q_measurement"), "Q-QB-001"),
    TopicSpec("quantum-gates", SUBJECT_ID, "Gates & States", "Pauli gates, Hadamard, Bloch sphere, interference.", ("q_states", "q_hadamard", "q_bloch", "q_interference"), "Q-GT-001"),
    TopicSpec("quantum-entanglement", SUBJECT_ID, "Entanglement & Teleportation", "Correlations, no-cloning, and teleportation.", ("q_entanglement", "q_teleport", "q_noclone"), "Q-EN-001"),
    TopicSpec("quantum-algorithms", SUBJECT_ID, "Algorithms & Error Correction", "Deutsch–Jozsa, Grover, Shor, and basic QEC.", ("q_circuits", "q_algorithms", "q_qec"), "Q-AL-001"),
)

CONCEPTS = (
    ConceptSpec("q_qubits", "quantum-qubits", SUBJECT_ID, "Qubits", "Two-level quantum systems used as information carriers.", "BEGINNER"),
    ConceptSpec("q_superposition", "quantum-qubits", SUBJECT_ID, "Superposition", "A qubit can be in a combination of |0> and |1> until measured.", "BEGINNER"),
    ConceptSpec("q_measurement", "quantum-qubits", SUBJECT_ID, "Measurement", "Measurement yields a definite classical outcome.", "BEGINNER"),
    ConceptSpec("q_states", "quantum-gates", SUBJECT_ID, "Quantum states", "Amplitudes describe a state vector.", "INTERMEDIATE"),
    ConceptSpec("q_hadamard", "quantum-gates", SUBJECT_ID, "Hadamard gate", "Creates equal superposition from |0> or |1>.", "INTERMEDIATE"),
    ConceptSpec("q_bloch", "quantum-gates", SUBJECT_ID, "Bloch sphere", "Geometric picture of a single-qubit state.", "INTERMEDIATE"),
    ConceptSpec("q_interference", "quantum-gates", SUBJECT_ID, "Interference", "Amplitudes can add or cancel.", "INTERMEDIATE"),
    ConceptSpec("q_entanglement", "quantum-entanglement", SUBJECT_ID, "Entanglement", "Joint states that cannot be factored into single-qubit states.", "INTERMEDIATE"),
    ConceptSpec("q_teleport", "quantum-entanglement", SUBJECT_ID, "Quantum teleportation", "Transfer of a state using entanglement and classical bits.", "ADVANCED"),
    ConceptSpec("q_noclone", "quantum-entanglement", SUBJECT_ID, "No-cloning theorem", "Unknown quantum states cannot be copied perfectly.", "ADVANCED"),
    ConceptSpec("q_circuits", "quantum-algorithms", SUBJECT_ID, "Quantum circuits", "Sequences of gates acting on qubits.", "ADVANCED"),
    ConceptSpec("q_algorithms", "quantum-algorithms", SUBJECT_ID, "Basic quantum algorithms", "Deutsch–Jozsa, Grover, and Shor at a conceptual level.", "ADVANCED"),
    ConceptSpec("q_qec", "quantum-algorithms", SUBJECT_ID, "Quantum error correction", "Protecting quantum information from noise.", "ADVANCED"),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("Q-QB-001", SUBJECT_ID, "quantum-qubits", "q_qubits", 1, "COMPARE",
       "What is the key difference between a classical bit and a qubit?",
       "A bit is only 0 or 1; a qubit can be in a superposition of |0> and |1>",
       "A classical bit is one of two values. A qubit has a state that can be a combination of |0> and |1> until you measure it.",
       choices=(
           "A bit is only 0 or 1; a qubit can be in a superposition of |0> and |1>",
           "A qubit is simply a faster classical bit",
           "Qubits store two classical bits at once that you can read together",
           "There is no difference",
       ),
       misconceptions=(Q_M003,), target="Q-M003",
       cues=("superposition", "bit", "measure"), family="Q-BIT-VS-QUBIT"),
    ch("Q-QB-002", SUBJECT_ID, "quantum-qubits", "q_superposition", 2, "TRUE_FALSE",
       "True or false: a qubit in superposition can be observed as both 0 and 1 during a single measurement.",
       "False",
       "Superposition is about amplitudes before measurement. One measurement gives one definite outcome, 0 or 1.",
       choices=("True", "False"),
       misconceptions=(Q_M001, Q_M002), target="Q-M001",
       cues=("definite", "one outcome", "not both"), family="Q-SUPERPOSITION",
       learn_more="Measurement samples the Born rule; it does not display both basis states."),
    ch("Q-QB-003", SUBJECT_ID, "quantum-qubits", "q_measurement", 2, "PREDICTION",
       "A qubit is placed into an equal superposition and measured once. What can you observe?",
       "Either 0 or 1, each with probability 1/2",
       "Equal superposition means 50/50. You see one bit, not both values at once.",
       choices=(
           "Either 0 or 1, each with probability 1/2",
           "Both 0 and 1 at the same time",
           "Always 0",
           "The qubit disappears",
       ),
       misconceptions=(Q_M001, Q_M002), target="Q-M001",
       cues=("probability", "one outcome", "equal"), family="Q-MEASURE"),
    ch("Q-QB-004", SUBJECT_ID, "quantum-qubits", "q_measurement", 2, "CONCEPT_CHECK",
       "After you measure a qubit and get 1, what happens if you measure it again immediately (no gates in between)?",
       "You get 1 again",
       "Measurement projects the state. A second immediate measurement of the same observable repeats that outcome.",
       cues=("project", "repeat", "same outcome"), family="Q-MEASURE",
       misconceptions=(Q_M008,), target="Q-M008"),
    ch("Q-QB-005", SUBJECT_ID, "quantum-qubits", "q_qubits", 2, "TRUE_FALSE",
       "True or false: a qubit is just a classical bit that runs faster.",
       "False",
       "Speed is not the difference. Qubits use superposition, interference, and entanglement — not a faster 0/1 flip.",
       choices=("True", "False"),
       misconceptions=(Q_M003,), target="Q-M003",
       cues=("not faster", "superposition", "interference"), family="Q-BIT-VS-QUBIT"),
    ch("Q-QB-006", SUBJECT_ID, "quantum-qubits", "q_superposition", 3, "REMEDIATION",
       "A learner said: 'A qubit is basically a bit that is both 0 and 1.' What is the better statement?",
       "It can be a combination of |0> and |1>, but a measurement gives one outcome",
       "The oversimplification hides measurement. Superposition is a combination of amplitudes, not seeing both results at once.",
       choices=(
           "It can be a combination of |0> and |1>, but a measurement gives one outcome",
           "It really is both 0 and 1 whenever you look",
           "It stores two classical bits you can read together",
           "It is only a faster bit",
       ),
       misconceptions=(Q_M001,), target="Q-M001",
       cues=("amplitudes", "one outcome", "combination"),
       strategies=("REMEDIATE", "PROBE", "DECREASE"), family="Q-SUPERPOSITION"),
    ch("Q-GT-001", SUBJECT_ID, "quantum-gates", "q_hadamard", 3, "TRUE_FALSE",
       "True or false: the Hadamard gate randomly chooses 0 or 1 the way a coin flip does.",
       "False",
       "Hadamard applies a definite unitary. Randomness appears at measurement, and amplitudes can later interfere.",
       choices=("True", "False"),
       misconceptions=(Q_M006,), target="Q-M006",
       cues=("unitary", "interference", "not a coin"), family="Q-HADAMARD"),
    ch("Q-GT-002", SUBJECT_ID, "quantum-gates", "q_hadamard", 3, "PREDICTION",
       "Start in |0>, apply H, then apply H again. What state do you get (ideal gates)?",
       "|0>",
       "H is its own inverse on this basis: H H |0> = |0>. That would not hold if H were a random coin flip.",
       misconceptions=(Q_M006,), target="Q-M006",
       cues=("inverse", "unitary", "back to 0"), family="Q-HADAMARD"),
    ch("Q-GT-003", SUBJECT_ID, "quantum-gates", "q_states", 3, "CONCEPT_CHECK",
       "X, Y, and Z are which family of single-qubit gates?",
       "Pauli gates",
       "The Pauli operators X, Y, and Z are the standard single-qubit bit and phase flips.",
       choices=("Pauli gates", "Turing gates", "Sorting gates", "Hash gates"),
       cues=("Pauli", "X", "Z")),
    ch("Q-GT-004", SUBJECT_ID, "quantum-gates", "q_bloch", 3, "MULTIPLE_CHOICE",
       "On the Bloch sphere, opposite poles typically represent:",
       "Orthogonal states such as |0> and |1>",
       "The Bloch sphere maps a qubit state to a point. Antipodal points are orthogonal states, e.g. |0> and |1>.",
       choices=("Orthogonal states such as |0> and |1>", "The same state twice", "Two classical bits", "Error-corrected logical qubits only"),
       cues=("orthogonal", "poles", "Bloch")),
    ch("Q-GT-005", SUBJECT_ID, "quantum-gates", "q_interference", 4, "EXPLANATION",
       "Why can two paths in a quantum algorithm cancel instead of just adding probabilities?",
       "Amplitudes can have opposite phase and cancel",
       "Probabilities come from |amplitude|². Phases let amplitudes interfere destructively, which probabilities alone cannot do.",
       cues=("amplitude", "phase", "cancel"), family="Q-INTERFERE"),
    ch("Q-GT-006", SUBJECT_ID, "quantum-gates", "q_states", 2, "DIRECT",
       "The Z gate leaves |0> unchanged and maps |1> to what?",
       "-|1>",
       "Z is a phase flip on |1>: Z|1> = −|1>.",
       cues=("phase", "Z", "|1>")),
    ch("Q-EN-001", SUBJECT_ID, "quantum-entanglement", "q_entanglement", 3, "TRUE_FALSE",
       "True or false: entanglement lets you send a usable message faster than light.",
       "False",
       "Measurement outcomes are correlated but individually random. You still need ordinary communication to compare results.",
       choices=("True", "False"),
       misconceptions=(Q_M004,), target="Q-M004",
       cues=("no signaling", "classical communication", "random"), family="Q-NOSIGNAL"),
    ch("Q-EN-002", SUBJECT_ID, "quantum-entanglement", "q_entanglement", 3, "EXPLANATION",
       "Explain why entanglement does not allow faster-than-light communication.",
       "Local outcomes look random until you compare them using ordinary communication",
       "Each party sees a random bit. The correlation appears only after they share results through a classical channel.",
       misconceptions=(Q_M004,), target="Q-M004",
       cues=("random", "compare", "classical channel"), family="Q-NOSIGNAL"),
    ch("Q-EN-003", SUBJECT_ID, "quantum-entanglement", "q_teleport", 4, "TRUE_FALSE",
       "True or false: quantum teleportation physically transports matter from one place to another.",
       "False",
       "Teleportation transfers a quantum state using entanglement and two classical bits. The particle does not travel.",
       choices=("True", "False"),
       misconceptions=(Q_M007,), target="Q-M007",
       cues=("state", "not matter", "classical bits"), family="Q-TELEPORT"),
    ch("Q-EN-004", SUBJECT_ID, "quantum-entanglement", "q_noclone", 4, "CONCEPT_CHECK",
       "The no-cloning theorem says you cannot:",
       "Make a perfect copy of an unknown quantum state",
       "A universal copier would violate linearity of quantum mechanics. Unknown states cannot be cloned perfectly.",
       choices=("Make a perfect copy of an unknown quantum state", "Measure a qubit", "Use a Hadamard gate", "Write a classical backup of 0 and 1"),
       cues=("clone", "unknown", "perfect copy")),
    ch("Q-EN-005", SUBJECT_ID, "quantum-entanglement", "q_teleport", 5, "SCENARIO",
       "Alice wants Bob to reconstruct her qubit. They share a Bell pair. What else must Alice send Bob?",
       "Two classical bits from her Bell measurement",
       "Teleportation consumes entanglement and requires two classical bits so Bob can apply the correcting gates.",
       misconceptions=(Q_M007, Q_M004),
       cues=("classical bits", "Bell", "correcting"), strategies=("INCREASE", "MAINTAIN"), family="Q-TELEPORT"),
    ch("Q-AL-001", SUBJECT_ID, "quantum-algorithms", "q_algorithms", 3, "TRUE_FALSE",
       "True or false: a quantum computer is faster for every computational problem.",
       "False",
       "Quantum advantage is problem-specific. Many tasks have no known quantum speedup, and there are proven limits.",
       choices=("True", "False"),
       misconceptions=(Q_M005,), target="Q-M005",
       cues=("not every", "problem-specific", "no universal speedup"), family="Q-SPEED"),
    ch("Q-AL-002", SUBJECT_ID, "quantum-algorithms", "q_algorithms", 4, "MULTIPLE_CHOICE",
       "Grover's algorithm is designed mainly to:",
       "Search an unstructured list with a quadratic speedup",
       "Grover finds a marked item among n possibilities in about √n queries, a quadratic — not exponential — speedup.",
       choices=(
           "Search an unstructured list with a quadratic speedup",
           "Factor large integers in polynomial time",
           "Send messages faster than light",
           "Clone unknown states",
       ),
       cues=("search", "quadratic", "square root"), family="Q-GROVER"),
    ch("Q-AL-003", SUBJECT_ID, "quantum-algorithms", "q_algorithms", 4, "COMPARE",
       "At a high level, how do Grover and Shor differ?",
       "Grover speeds unstructured search; Shor factors integers using period finding",
       "They solve different problems. Shor's exponential speedup for factoring is not the same as Grover's quadratic search speedup.",
       cues=("factor", "period", "search"), family="Q-SHOR"),
    ch("Q-AL-004", SUBJECT_ID, "quantum-algorithms", "q_algorithms", 3, "CONCEPT_CHECK",
       "Deutsch–Jozsa tells you whether a promised function is:",
       "Constant or balanced",
       "With that promise, one quantum query can distinguish constant from balanced functions.",
       choices=("Constant or balanced", "Sorted or unsorted", "Prime or composite", "Encrypted or plaintext"),
       cues=("constant", "balanced", "promise")),
    ch("Q-AL-005", SUBJECT_ID, "quantum-algorithms", "q_qec", 5, "CONCEPT_CHECK",
       "Quantum error correction must protect quantum information without:",
       "Measuring the data qubits in a way that collapses the encoded state",
       "You infer errors from ancilla/syndrome measurements so the logical state is not destroyed.",
       cues=("syndrome", "ancilla", "not collapse"), family="Q-QEC"),
    ch("Q-AL-006", SUBJECT_ID, "quantum-algorithms", "q_circuits", 4, "SEQUENCE",
       "A simple circuit: |0> — H — measure. What distribution do you expect?",
       "About 50% 0 and 50% 1",
       "H|0> is equal superposition. Measurement then samples 0 or 1 with equal probability.",
       misconceptions=(Q_M006,),
       cues=("Hadamard", "equal", "measure"), family="Q-CIRCUIT"),
    ch("Q-AL-007", SUBJECT_ID, "quantum-algorithms", "q_measurement", 3, "TRUE_FALSE",
       "True or false: you can reverse a measurement and restore the pre-measurement superposition with no extra information.",
       "False",
       "A projective measurement is not a unitary you can undo in general. The superposition is lost unless you had a copy or a reversible embedding.",
       choices=("True", "False"),
       misconceptions=(Q_M008,), target="Q-M008",
       cues=("not unitary", "cannot undo", "projection"), family="Q-MEASURE"),
)
