"""Space and astronomy catalog."""

from __future__ import annotations

from adapt.content.models import CatalogChallenge, ConceptSpec, TopicSpec, ch

SUBJECT_ID = "space"

TOPICS = (
    TopicSpec("space-solar", SUBJECT_ID, "Solar System", "The Sun, planets, and nearby bodies.", ("space_solar",), "SP-SOL-001"),
    TopicSpec("space-stars", SUBJECT_ID, "Stars", "How stars shine and evolve.", ("space_stars",), "SP-ST-001"),
    TopicSpec("space-galaxies", SUBJECT_ID, "Galaxies", "Collections of stars and dark matter.", ("space_galaxies",), "SP-GAL-001"),
    TopicSpec("space-black-holes", SUBJECT_ID, "Black Holes", "Gravity so strong light cannot escape.", ("space_bh",), "SP-BH-001"),
    TopicSpec("space-orbital", SUBJECT_ID, "Orbital Mechanics", "Why satellites stay in orbit.", ("space_orbit",), "SP-ORB-001"),
    TopicSpec("space-cosmology", SUBJECT_ID, "Cosmology", "The large-scale universe.", ("space_cosmo",), "SP-COS-001"),
)

CONCEPTS = (
    ConceptSpec("space_solar", "space-solar", SUBJECT_ID, "Solar system structure", "Sun-centered planets and small bodies."),
    ConceptSpec("space_stars", "space-stars", SUBJECT_ID, "Stellar properties", "Fusion and stellar life cycles."),
    ConceptSpec("space_galaxies", "space-galaxies", SUBJECT_ID, "Galaxies", "Star systems on a cosmic scale."),
    ConceptSpec("space_bh", "space-black-holes", SUBJECT_ID, "Black holes", "Event horizons and collapse remnants."),
    ConceptSpec("space_orbit", "space-orbital", SUBJECT_ID, "Orbits", "Free-fall around a gravitating body."),
    ConceptSpec("space_cosmo", "space-cosmology", SUBJECT_ID, "Cosmology", "Expansion and large-scale structure."),
)

CHALLENGES: tuple[CatalogChallenge, ...] = (
    ch("SP-SOL-001", SUBJECT_ID, "space-solar", "space_solar", 1, "CONCEPT_CHECK",
       "The solar system is centered on:",
       "The Sun",
       "Planets orbit the Sun, which holds most of the system's mass.",
       choices=("The Sun", "Earth", "The Moon", "Jupiter"),
       cues=("Sun", "center", "orbit")),
    ch("SP-SOL-002", SUBJECT_ID, "space-solar", "space_solar", 2, "COMPARE",
       "How do terrestrial planets differ from gas giants in our solar system?",
       "Terrestrial planets are rocky and closer in; gas giants are larger and farther out",
       "Mercury through Mars are rocky. Jupiter and Saturn are giant and hydrogen-rich.",
       cues=("rocky", "gas", "distance")),
    ch("SP-SOL-003", SUBJECT_ID, "space-solar", "space_solar", 2, "TRUE_FALSE",
       "True or false: Pluto is classified as a dwarf planet, not one of the eight major planets.",
       "True",
       "The IAU classifies Pluto as a dwarf planet in the trans-Neptunian region.",
       choices=("True", "False"),
       cues=("dwarf", "eight", "IAU")),
    ch("SP-ST-001", SUBJECT_ID, "space-stars", "space_stars", 2, "CONCEPT_CHECK",
       "Main-sequence stars shine primarily because of:",
       "Nuclear fusion in the core",
       "Hydrogen fuses to helium, releasing energy that supports the star.",
       choices=("Nuclear fusion in the core", "The star burning coal", "Reflected sunlight only", "Chemical combustion like a fire"),
       cues=("fusion", "hydrogen", "core")),
    ch("SP-ST-002", SUBJECT_ID, "space-stars", "space_stars", 3, "SEQUENCE",
       "A Sun-like star's later stages, in order, are best described as:",
       "Red giant, then white dwarf",
       "After the main sequence, a solar-mass star becomes a red giant and leaves a white dwarf remnant.",
       cues=("red giant", "white dwarf", "main sequence")),
    ch("SP-ST-003", SUBJECT_ID, "space-stars", "space_stars", 3, "PREDICTION",
       "If a star is much more massive than the Sun, its likely remnant after a supernova is:",
       "A neutron star or black hole",
       "High-mass stars do not end as white dwarfs; cores collapse to neutron stars or black holes.",
       cues=("massive", "supernova", "collapse")),
    ch("SP-GAL-001", SUBJECT_ID, "space-galaxies", "space_galaxies", 2, "CONCEPT_CHECK",
       "The Milky Way is:",
       "A barred spiral galaxy that contains the Sun",
       "We live in a barred spiral galaxy of stars, gas, dust, and dark matter.",
       choices=("A barred spiral galaxy that contains the Sun", "The only galaxy", "A single star", "A solar system"),
       cues=("spiral", "Milky Way", "Sun")),
    ch("SP-GAL-002", SUBJECT_ID, "space-galaxies", "space_galaxies", 3, "COMPARE",
       "What is a difference between a spiral galaxy and an elliptical galaxy?",
       "Spirals have disks and arms; ellipticals are rounder with older stars and little dust",
       "Morphology traces star-formation history: spirals still have gas and arms; ellipticals are smoother.",
       cues=("disk", "arms", "elliptical")),
    ch("SP-BH-001", SUBJECT_ID, "space-black-holes", "space_bh", 2, "CONCEPT_CHECK",
       "The event horizon of a black hole is:",
       "The boundary beyond which light cannot escape",
       "Inside the event horizon, escape speed exceeds the speed of light.",
       choices=("The boundary beyond which light cannot escape", "The solid surface you can stand on", "A glowing fireball", "Earth's atmosphere"),
       cues=("escape", "light", "horizon")),
    ch("SP-BH-002", SUBJECT_ID, "space-black-holes", "space_bh", 3, "TRUE_FALSE",
       "True or false: black holes suck in everything in the galaxy like a vacuum cleaner from any distance.",
       "False",
       "At a distance, gravity is the same as any equal mass. You must get close to the horizon for dramatic effects.",
       choices=("True", "False"),
       cues=("same gravity", "distance", "not a vacuum")),
    ch("SP-BH-003", SUBJECT_ID, "space-black-holes", "space_bh", 4, "EXPLANATION",
       "Why can light not escape from inside a black hole's event horizon?",
       "Spacetime curvature / escape speed exceeds the speed of light",
       "General relativity: outgoing light is trapped. No signal from inside reaches distant observers.",
       cues=("escape speed", "curvature", "light"), strategies=("INCREASE", "PROBE")),
    ch("SP-ORB-001", SUBJECT_ID, "space-orbital", "space_orbit", 2, "CONCEPT_CHECK",
       "An orbiting satellite is best described as:",
       "In continuous free-fall around Earth",
       "It falls under gravity but has enough sideways speed to miss the Earth.",
       choices=("In continuous free-fall around Earth", "Floating because there is no gravity in space", "Attached by an invisible string", "Stationary above one point only by magic"),
       cues=("free-fall", "sideways", "gravity")),
    ch("SP-ORB-002", SUBJECT_ID, "space-orbital", "space_orbit", 3, "TRUE_FALSE",
       "True or false: astronauts float because Earth's gravity is zero on the ISS.",
       "False",
       "Gravity at ISS altitude is still strong. They float because they and the station are in free-fall together.",
       choices=("True", "False"),
       cues=("free-fall", "not zero gravity", "ISS")),
    ch("SP-ORB-003", SUBJECT_ID, "space-orbital", "space_orbit", 4, "APPLICATION",
       "To raise a circular orbit's altitude, you typically need to:",
       "Increase orbital energy (e.g. speed up at the right point)",
       "Higher circular orbits have higher total energy. A prograde burn raises the opposite side.",
       cues=("energy", "prograde", "higher"), strategies=("INCREASE", "MAINTAIN")),
    ch("SP-COS-001", SUBJECT_ID, "space-cosmology", "space_cosmo", 2, "CONCEPT_CHECK",
       "Hubble's observation that distant galaxies recede is evidence that:",
       "Space is expanding",
       "Redshift increasing with distance is the expansion of space on large scales.",
       choices=("Space is expanding", "Earth is the center of everything", "Stars are burning out today only", "The solar system is shrinking"),
       cues=("expanding", "redshift", "distance")),
    ch("SP-COS-002", SUBJECT_ID, "space-cosmology", "space_cosmo", 3, "TRUE_FALSE",
       "True or false: the Big Bang was an explosion of matter into a pre-existing empty room.",
       "False",
       "It is better described as the early hot, dense expansion of space itself, not a bomb in a warehouse.",
       choices=("True", "False"),
       cues=("space itself", "not a bomb", "early universe")),
    ch("SP-COS-003", SUBJECT_ID, "space-cosmology", "space_cosmo", 3, "MULTIPLE_CHOICE",
       "Cosmic microwave background radiation is:",
       "Leftover light from when the universe became transparent",
       "The CMB is relic radiation from recombination, now cooled by expansion.",
       choices=(
           "Leftover light from when the universe became transparent",
           "Light from the Sun only",
           "Wi-Fi interference",
           "Glows from Earth's core",
       ),
       cues=("CMB", "recombination", "relic")),
)
